# Korelace podílu prefenčních hlasů pro kandidátky Motoristé a indexů pro obce v jednotlivých krajích

Korelace indexů s podíly prefenčních hlasů v obcích v daných krajích. Vždy pro každou stranu zvlášť.

In [1]:
import pandas as pd

# obce_kraje
obce_kraje = pd.read_csv("obce_kraje.csv")
obce_kraje = obce_kraje.rename(columns={"OBEC_PREZ": "KodObec"})

# hlasy stran za obec
hlasy_strany = pd.read_csv("hlasy_strany_obce.csv")

In [2]:
# Motoriste - kandidátky s aspoň jednou ženou

strany_s_kandidatkami = pd.read_csv("strany_s_kandidatkami_obec.csv")
Motoriste = strany_s_kandidatkami[strany_s_kandidatkami["KSTRANA"] == 20]

# merge s celkovým počtem hlasů pro stranu + výpočet podílu preferenčních hlasů
Motoriste = Motoriste.merge(hlasy_strany, on=["KodObec", "KSTRANA"], how="left")
Motoriste["podil_preferencnich_z_hlasu"] = Motoriste["Preferencni_hlasy_celkem_obce"] / Motoriste["hlasy_strany_celkem"]

In [3]:
# 2 - Středočeský kraj
obce_kraj2 = obce_kraje[obce_kraje["VOLKRAJ"] == 2]["KodObec"].tolist()
Motoriste_kraj2 = Motoriste[Motoriste["KodObec"].isin(obce_kraj2)]

Motoriste_kraj2[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.089602,0.384078,0.125779,0.017827,0.066458,0.053803,-0.065423,-0.030245,0.065279,0.775885
Preferencni_hlasy_celkem_obce,0.089602,1.000000,0.121667,0.538867,-0.217367,0.043936,0.028389,-0.056211,-0.036942,0.203973,0.203292
podil_preferencnich_z_hlasu,0.384078,0.121667,1.000000,0.090094,-0.016609,0.078402,0.032505,-0.107752,-0.084276,0.005730,0.397590
index_vybavenosti,0.125779,0.538867,0.090094,1.000000,-0.073444,0.159390,0.185274,-0.167843,-0.048576,0.302719,0.331928
index_socioekonomicky,0.017827,-0.217367,-0.016609,-0.073444,1.000000,0.507521,0.391503,-0.309064,-0.058529,0.393322,0.035586
index_stari,0.066458,0.043936,0.078402,0.159390,0.507521,1.000000,0.643812,-0.704867,-0.286463,0.107747,0.130135
index_zavisloti,0.053803,0.028389,0.032505,0.185274,0.391503,0.643812,1.000000,-0.263495,0.359297,0.202459,0.096260
index_zavisloti_2,-0.065423,-0.056211,-0.107752,-0.167843,-0.309064,-0.704867,-0.263495,1.000000,0.805571,0.016001,-0.128498
index_ekonom_zatizeni,-0.030245,-0.036942,-0.084276,-0.048576,-0.058529,-0.286463,0.359297,0.805571,1.000000,0.139831,-0.065187
index_vzdelani,0.065279,0.203973,0.005730,0.302719,0.393322,0.107747,0.202459,0.016001,0.139831,1.000000,0.168275
kvartal,0.775885,0.203292,0.397590,0.331928,0.035586,0.130135,0.096260,-0.128498,-0.065187,0.168275,1.000000

In [4]:
# 3 - Jihočeský kraj
obce_kraj3 = obce_kraje[obce_kraje["VOLKRAJ"] == 3]["KodObec"].tolist()
Motoriste_kraj3 = Motoriste[Motoriste["KodObec"].isin(obce_kraj3)]

Motoriste_kraj3[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.057419,0.273258,0.130025,-0.062954,-0.033382,-0.049461,-0.033430,-0.056948,-0.044154,0.779586
Preferencni_hlasy_celkem_obce,0.057419,1.000000,0.069693,0.415631,-0.231564,-0.031341,-0.009356,0.000960,-0.004271,0.193533,0.172945
podil_preferencnich_z_hlasu,0.273258,0.069693,1.000000,-0.005112,-0.049555,-0.034121,-0.018996,0.073916,0.055562,-0.094418,0.340935
index_vybavenosti,0.130025,0.415631,-0.005112,1.000000,-0.299594,-0.023033,-0.015195,-0.099280,-0.096941,0.170991,0.334407
index_socioekonomicky,-0.062954,-0.231564,-0.049555,-0.299594,1.000000,0.315775,0.252857,-0.209560,-0.048453,0.266417,-0.098876
index_stari,-0.033382,-0.031341,-0.034121,-0.023033,0.315775,1.000000,0.676321,-0.680300,-0.236514,0.022151,-0.022474
index_zavisloti,-0.049461,-0.009356,-0.018996,-0.015195,0.252857,0.676321,1.000000,-0.099201,0.459555,0.157425,-0.008700
index_zavisloti_2,-0.033430,0.000960,0.073916,-0.099280,-0.209560,-0.680300,-0.099201,1.000000,0.838180,0.074132,-0.031581
index_ekonom_zatizeni,-0.056948,-0.004271,0.055562,-0.096941,-0.048453,-0.236514,0.459555,0.838180,1.000000,0.152538,-0.032957
index_vzdelani,-0.044154,0.193533,-0.094418,0.170991,0.266417,0.022151,0.157425,0.074132,0.152538,1.000000,0.046660
kvartal,0.779586,0.172945,0.340935,0.334407,-0.098876,-0.022474,-0.008700,-0.031581,-0.032957,0.046660,1.000000

In [5]:
# 4 - Plzeňský kraj
obce_kraj4 = obce_kraje[obce_kraje["VOLKRAJ"] == 4]["KodObec"].tolist()
Motoriste_kraj4 = Motoriste[Motoriste["KodObec"].isin(obce_kraj4)]

Motoriste_kraj4[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.044207,0.348596,0.254756,-0.076546,0.016717,0.011814,-0.049746,-0.040721,-0.062542,0.856052
Preferencni_hlasy_celkem_obce,0.044207,1.000000,0.129235,0.261406,-0.148166,-0.016735,-0.024618,-0.021653,-0.034891,0.121863,0.071107
podil_preferencnich_z_hlasu,0.348596,0.129235,1.000000,0.019148,0.024333,0.118932,0.033547,-0.110666,-0.086415,-0.041739,0.408238
index_vybavenosti,0.254756,0.261406,0.019148,1.000000,-0.202728,-0.039217,-0.018291,-0.076952,-0.084084,0.162284,0.396164
index_socioekonomicky,-0.076546,-0.148166,0.024333,-0.202728,1.000000,0.221046,0.145926,-0.204384,-0.111135,0.220549,-0.068007
index_stari,0.016717,-0.016735,0.118932,-0.039217,0.221046,1.000000,0.678804,-0.732058,-0.308004,-0.226386,0.008026
index_zavisloti,0.011814,-0.024618,0.033547,-0.018291,0.145926,0.678804,1.000000,-0.222993,0.363709,-0.022860,-0.019719
index_zavisloti_2,-0.049746,-0.021653,-0.110666,-0.076952,-0.204384,-0.732058,-0.222993,1.000000,0.826953,0.242528,-0.088435
index_ekonom_zatizeni,-0.040721,-0.034891,-0.086415,-0.084084,-0.111135,-0.308004,0.363709,0.826953,1.000000,0.218568,-0.095880
index_vzdelani,-0.062542,0.121863,-0.041739,0.162284,0.220549,-0.226386,-0.022860,0.242528,0.218568,1.000000,0.019036
kvartal,0.856052,0.071107,0.408238,0.396164,-0.068007,0.008026,-0.019719,-0.088435,-0.095880,0.019036,1.000000

In [6]:
# 5 - Karlovarský kraj
obce_kraj5 = obce_kraje[obce_kraje["VOLKRAJ"] == 5]["KodObec"].tolist()
Motoriste_kraj5 = Motoriste[Motoriste["KodObec"].isin(obce_kraj5)]

Motoriste_kraj5[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.054263,-0.030433,0.149983,-0.085840,-0.045664,-0.015261,0.079985,0.065967,-0.019817,0.681419
Preferencni_hlasy_celkem_obce,0.054263,1.000000,0.155631,0.574612,-0.391471,-0.147022,-0.082369,0.152474,0.096304,0.189164,0.198442
podil_preferencnich_z_hlasu,-0.030433,0.155631,1.000000,0.000005,0.049464,-0.146796,0.023485,0.143183,0.146168,0.019122,0.086747
index_vybavenosti,0.149983,0.574612,0.000005,1.000000,-0.618620,-0.216486,-0.025961,0.257557,0.225229,0.156888,0.476578
index_socioekonomicky,-0.085840,-0.391471,0.049464,-0.618620,1.000000,-0.012980,-0.101386,-0.108478,-0.156943,0.362101,-0.310912
index_stari,-0.045664,-0.147022,-0.146796,-0.216486,-0.012980,1.000000,0.656262,-0.726865,-0.313404,-0.274341,-0.070704
index_zavisloti,-0.015261,-0.082369,0.023485,-0.025961,-0.101386,0.656262,1.000000,-0.166058,0.398244,-0.087961,0.019003
index_zavisloti_2,0.079985,0.152474,0.143183,0.257557,-0.108478,-0.726865,-0.166058,1.000000,0.838413,0.231806,0.095891
index_ekonom_zatizeni,0.065967,0.096304,0.146168,0.225229,-0.156943,-0.313404,0.398244,0.838413,1.000000,0.165432,0.099701
index_vzdelani,-0.019817,0.189164,0.019122,0.156888,0.362101,-0.274341,-0.087961,0.231806,0.165432,1.000000,0.006206
kvartal,0.681419,0.198442,0.086747,0.476578,-0.310912,-0.070704,0.019003,0.095891,0.099701,0.006206,1.000000

In [7]:
# 6 - Ústecký kraj
obce_kraj6 = obce_kraje[obce_kraje["VOLKRAJ"] == 6]["KodObec"].tolist()
Motoriste_kraj6 = Motoriste[Motoriste["KodObec"].isin(obce_kraj6)]

Motoriste_kraj6[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.036664,0.085821,0.017554,0.005996,0.037213,0.063744,0.030969,0.062180,0.038912,0.691266
Preferencni_hlasy_celkem_obce,0.036664,1.000000,0.089348,0.498590,-0.553197,-0.060787,0.005278,0.043809,0.042007,0.124649,0.177263
podil_preferencnich_z_hlasu,0.085821,0.089348,1.000000,-0.010203,-0.071944,0.000874,0.159341,0.069601,0.148465,-0.051125,0.217917
index_vybavenosti,0.017554,0.498590,-0.010203,1.000000,-0.607526,-0.091512,0.019986,0.052231,0.057495,0.008805,0.238702
index_socioekonomicky,0.005996,-0.553197,-0.071944,-0.607526,1.000000,-0.001225,-0.062679,-0.027511,-0.058514,0.330317,-0.174488
index_stari,0.037213,-0.060787,0.000874,-0.091512,-0.001225,1.000000,0.647109,-0.723054,-0.295875,-0.287304,0.016364
index_zavisloti,0.063744,0.005278,0.159341,0.019986,-0.062679,0.647109,1.000000,-0.094696,0.456677,-0.068349,-0.011394
index_zavisloti_2,0.030969,0.043809,0.069601,0.052231,-0.027511,-0.723054,-0.094696,1.000000,0.842390,0.343997,-0.027853
index_ekonom_zatizeni,0.062180,0.042007,0.148465,0.057495,-0.058514,-0.295875,0.456677,0.842390,1.000000,0.270415,-0.031058
index_vzdelani,0.038912,0.124649,-0.051125,0.008805,0.330317,-0.287304,-0.068349,0.343997,0.270415,1.000000,0.034785
kvartal,0.691266,0.177263,0.217917,0.238702,-0.174488,0.016364,-0.011394,-0.027853,-0.031058,0.034785,1.000000

In [8]:
# 7 - Liberecký kraj
obce_kraj7 = obce_kraje[obce_kraje["VOLKRAJ"] == 7]["KodObec"].tolist()
Motoriste_kraj7 = Motoriste[Motoriste["KodObec"].isin(obce_kraj7)]

Motoriste_kraj7[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.058607,0.257075,0.284241,-0.070699,0.219258,0.136337,-0.170190,-0.084414,0.061662,0.756923
Preferencni_hlasy_celkem_obce,0.058607,1.000000,0.175365,0.367694,-0.325442,-0.035099,-0.028466,-0.004413,-0.019699,0.122399,0.140185
podil_preferencnich_z_hlasu,0.257075,0.175365,1.000000,0.061214,-0.027709,0.050627,0.094048,0.028320,0.077928,0.085360,0.344111
index_vybavenosti,0.284241,0.367694,0.061214,1.000000,-0.466579,-0.096433,-0.033404,0.008578,-0.010263,0.046042,0.448131
index_socioekonomicky,-0.070699,-0.325442,-0.027709,-0.466579,1.000000,0.221101,0.187048,-0.129322,-0.018483,0.463357,-0.155668
index_stari,0.219258,-0.035099,0.050627,-0.096433,0.221101,1.000000,0.634322,-0.760614,-0.363581,-0.000746,0.149051
index_zavisloti,0.136337,-0.028466,0.094048,-0.033404,0.187048,0.634322,1.000000,-0.168561,0.389672,0.243425,0.118764
index_zavisloti_2,-0.170190,-0.004413,0.028320,0.008578,-0.129322,-0.760614,-0.168561,1.000000,0.842092,0.171344,-0.102682
index_ekonom_zatizeni,-0.084414,-0.019699,0.077928,-0.010263,-0.018483,-0.363581,0.389672,0.842092,1.000000,0.293284,-0.030955
index_vzdelani,0.061662,0.122399,0.085360,0.046042,0.463357,-0.000746,0.243425,0.171344,0.293284,1.000000,0.077614
kvartal,0.756923,0.140185,0.344111,0.448131,-0.155668,0.149051,0.118764,-0.102682,-0.030955,0.077614,1.000000

In [9]:
# 8 - Královéhradecký kraj
obce_kraj8 = obce_kraje[obce_kraje["VOLKRAJ"] == 8]["KodObec"].tolist()
Motoriste_kraj8 = Motoriste[Motoriste["KodObec"].isin(obce_kraj8)]

Motoriste_kraj8[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.026708,0.018713,0.121164,0.008480,-0.060656,-0.093298,-0.024230,-0.076768,0.071960,0.783400
Preferencni_hlasy_celkem_obce,0.026708,1.000000,0.081899,0.397852,-0.298445,-0.110488,-0.046166,0.112351,0.065299,0.208860,0.146541
podil_preferencnich_z_hlasu,0.018713,0.081899,1.000000,0.056112,0.017373,-0.061460,-0.083445,0.003658,-0.047621,0.129968,0.255503
index_vybavenosti,0.121164,0.397852,0.056112,1.000000,-0.373739,-0.188341,-0.073702,0.153055,0.082393,0.211951,0.392802
index_socioekonomicky,0.008480,-0.298445,0.017373,-0.373739,1.000000,0.292474,0.150508,-0.270885,-0.133640,0.249762,-0.047661
index_stari,-0.060656,-0.110488,-0.061460,-0.188341,0.292474,1.000000,0.674605,-0.717747,-0.186651,-0.008234,-0.117174
index_zavisloti,-0.093298,-0.046166,-0.083445,-0.073702,0.150508,0.674605,1.000000,-0.058072,0.558863,0.057617,-0.095230
index_zavisloti_2,-0.024230,0.112351,0.003658,0.153055,-0.270885,-0.717747,-0.058072,1.000000,0.795406,0.073688,0.018847
index_ekonom_zatizeni,-0.076768,0.065299,-0.047621,0.082393,-0.133640,-0.186651,0.558863,0.795406,1.000000,0.096189,-0.042159
index_vzdelani,0.071960,0.208860,0.129968,0.211951,0.249762,-0.008234,0.057617,0.073688,0.096189,1.000000,0.167137
kvartal,0.783400,0.146541,0.255503,0.392802,-0.047661,-0.117174,-0.095230,0.018847,-0.042159,0.167137,1.000000

In [10]:
# 9 - Pardubický kraj
obce_kraj9 = obce_kraje[obce_kraje["VOLKRAJ"] == 9]["KodObec"].tolist()
Motoriste_kraj9 = Motoriste[Motoriste["KodObec"].isin(obce_kraj9)]

Motoriste_kraj9[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.014781,0.143187,0.026435,-0.027375,-0.014356,0.026679,-0.016792,-0.000363,0.006601,0.572314
Preferencni_hlasy_celkem_obce,0.014781,1.000000,0.198414,0.353726,-0.236572,-0.042209,-0.016588,0.018451,0.007466,0.202389,0.066994
podil_preferencnich_z_hlasu,0.143187,0.198414,1.000000,0.039384,0.090644,0.081940,0.062574,-0.080962,-0.038430,0.054861,0.143927
index_vybavenosti,0.026435,0.353726,0.039384,1.000000,-0.172503,0.004100,0.036878,-0.072959,-0.045467,0.267926,0.128729
index_socioekonomicky,-0.027375,-0.236572,0.090644,-0.172503,1.000000,0.363772,0.227740,-0.272981,-0.120274,0.336259,-0.112240
index_stari,-0.014356,-0.042209,0.081940,0.004100,0.363772,1.000000,0.607954,-0.745911,-0.336607,-0.000405,-0.005756
index_zavisloti,0.026679,-0.016588,0.062574,0.036878,0.227740,0.607954,1.000000,-0.124840,0.442456,0.108128,0.030235
index_zavisloti_2,-0.016792,0.018451,-0.080962,-0.072959,-0.272981,-0.745911,-0.124840,1.000000,0.834539,0.150488,0.011436
index_ekonom_zatizeni,-0.000363,0.007466,-0.038430,-0.045467,-0.120274,-0.336607,0.442456,0.834539,1.000000,0.196063,0.027126
index_vzdelani,0.006601,0.202389,0.054861,0.267926,0.336259,-0.000405,0.108128,0.150488,0.196063,1.000000,-0.016595
kvartal,0.572314,0.066994,0.143927,0.128729,-0.112240,-0.005756,0.030235,0.011436,0.027126,-0.016595,1.000000

In [11]:
# 10 - Kraj Vysočina
obce_kraj10 = obce_kraje[obce_kraje["VOLKRAJ"] == 10]["KodObec"].tolist()
Motoriste_kraj10 = Motoriste[Motoriste["KodObec"].isin(obce_kraj10)]

Motoriste_kraj10[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.053493,0.164376,0.086848,0.075462,0.089171,0.051893,-0.092077,-0.056138,-0.002176,0.684048
Preferencni_hlasy_celkem_obce,0.053493,1.000000,0.096532,0.442661,-0.143193,-0.062942,-0.046155,0.012118,-0.014565,0.199463,0.159766
podil_preferencnich_z_hlasu,0.164376,0.096532,1.000000,-0.031341,-0.030448,-0.054807,-0.026353,0.046758,0.028507,-0.077870,0.213521
index_vybavenosti,0.086848,0.442661,-0.031341,1.000000,-0.015608,-0.073652,-0.027303,-0.037752,-0.050136,0.296898,0.227599
index_socioekonomicky,0.075462,-0.143193,-0.030448,-0.015608,1.000000,0.202912,0.166135,-0.096917,0.003163,0.248324,-0.010794
index_stari,0.089171,-0.062942,-0.054807,-0.073652,0.202912,1.000000,0.704964,-0.634734,-0.193142,-0.018131,0.055202
index_zavisloti,0.051893,-0.046155,-0.026353,-0.027303,0.166135,0.704964,1.000000,-0.160812,0.409602,0.135936,0.024891
index_zavisloti_2,-0.092077,0.012118,0.046758,-0.037752,-0.096917,-0.634734,-0.160812,1.000000,0.834523,0.091919,-0.051625
index_ekonom_zatizeni,-0.056138,-0.014565,0.028507,-0.050136,0.003163,-0.193142,0.409602,0.834523,1.000000,0.160845,-0.033822
index_vzdelani,-0.002176,0.199463,-0.077870,0.296898,0.248324,-0.018131,0.135936,0.091919,0.160845,1.000000,-0.026791
kvartal,0.684048,0.159766,0.213521,0.227599,-0.010794,0.055202,0.024891,-0.051625,-0.033822,-0.026791,1.000000

In [12]:
# 11 - Jihomoravský kraj
obce_kraj11 = obce_kraje[obce_kraje["VOLKRAJ"] == 11]["KodObec"].tolist()
Motoriste_kraj11 = Motoriste[Motoriste["KodObec"].isin(obce_kraj11)]

Motoriste_kraj11[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.023446,0.234264,0.084986,0.008626,-0.019876,-0.043159,-0.026085,-0.054556,0.001810,0.756029
Preferencni_hlasy_celkem_obce,0.023446,1.000000,0.156247,0.178559,-0.416278,-0.024179,-0.022867,0.000018,-0.015749,0.149956,0.090061
podil_preferencnich_z_hlasu,0.234264,0.156247,1.000000,0.014478,-0.003282,-0.026107,-0.052748,-0.045327,-0.079466,-0.008707,0.265762
index_vybavenosti,0.084986,0.178559,0.014478,1.000000,-0.061880,-0.022330,0.037522,-0.041138,-0.013243,0.331782,0.284494
index_socioekonomicky,0.008626,-0.416278,-0.003282,-0.061880,1.000000,0.423435,0.409733,-0.252036,0.042870,0.316145,-0.019474
index_stari,-0.019876,-0.024179,-0.026107,-0.022330,0.423435,1.000000,0.749480,-0.734964,-0.182037,0.065608,-0.046923
index_zavisloti,-0.043159,-0.022867,-0.052748,0.037522,0.409733,0.749480,1.000000,-0.289317,0.414391,0.198344,-0.048326
index_zavisloti_2,-0.026085,0.000018,-0.045327,-0.041138,-0.252036,-0.734964,-0.289317,1.000000,0.751287,0.080220,-0.030230
index_ekonom_zatizeni,-0.054556,-0.015749,-0.079466,-0.013243,0.042870,-0.182037,0.414391,0.751287,1.000000,0.213020,-0.062060
index_vzdelani,0.001810,0.149956,-0.008707,0.331782,0.316145,0.065608,0.198344,0.080220,0.213020,1.000000,0.084375
kvartal,0.756029,0.090061,0.265762,0.284494,-0.019474,-0.046923,-0.048326,-0.030230,-0.062060,0.084375,1.000000

In [13]:
# 12 - Olomoucký kraj
obce_kraj12 = obce_kraje[obce_kraje["VOLKRAJ"] == 12]["KodObec"].tolist()
Motoriste_kraj12 = Motoriste[Motoriste["KodObec"].isin(obce_kraj12)]

Motoriste_kraj12[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.011343,-0.037983,0.129294,0.008716,0.078952,0.053426,-0.130686,-0.093796,0.076035,0.764964
Preferencni_hlasy_celkem_obce,0.011343,1.000000,0.080967,0.372418,-0.315847,-0.066178,-0.023109,0.044079,0.029101,0.253805,0.123327
podil_preferencnich_z_hlasu,-0.037983,0.080967,1.000000,-0.058704,-0.001627,0.020888,0.044669,-0.029205,-0.004658,0.000761,0.211368
index_vybavenosti,0.129294,0.372418,-0.058704,1.000000,-0.294375,-0.092443,-0.036217,0.013712,-0.005407,0.253004,0.323144
index_socioekonomicky,0.008716,-0.315847,-0.001627,-0.294375,1.000000,0.316166,0.244344,-0.227713,-0.088094,0.352269,-0.048365
index_stari,0.078952,-0.066178,0.020888,-0.092443,0.316166,1.000000,0.712711,-0.588869,-0.187548,-0.004098,0.068083
index_zavisloti,0.053426,-0.023109,0.044669,-0.036217,0.244344,0.712711,1.000000,-0.105706,0.400723,0.082185,0.086329
index_zavisloti_2,-0.130686,0.044079,-0.029205,0.013712,-0.227713,-0.588869,-0.105706,1.000000,0.868707,0.037649,-0.137916
index_ekonom_zatizeni,-0.093796,0.029101,-0.004658,-0.005407,-0.088094,-0.187548,0.400723,0.868707,1.000000,0.075887,-0.084068
index_vzdelani,0.076035,0.253805,0.000761,0.253004,0.352269,-0.004098,0.082185,0.037649,0.075887,1.000000,0.163477
kvartal,0.764964,0.123327,0.211368,0.323144,-0.048365,0.068083,0.086329,-0.137916,-0.084068,0.163477,1.000000

In [14]:
# 13 - Zlínský kraj
obce_kraj13 = obce_kraje[obce_kraje["VOLKRAJ"] == 13]["KodObec"].tolist()
Motoriste_kraj13 = Motoriste[Motoriste["KodObec"].isin(obce_kraj13)]

Motoriste_kraj13[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.003934,0.049721,0.083859,0.039504,-0.008985,-0.038852,-0.042118,-0.064786,0.092745,0.569310
Preferencni_hlasy_celkem_obce,0.003934,1.000000,0.088973,0.405231,-0.299652,-0.119885,-0.054756,0.140109,0.091288,0.343186,0.067998
podil_preferencnich_z_hlasu,0.049721,0.088973,1.000000,0.002748,0.011855,0.010709,0.010960,0.031753,0.036467,-0.019820,0.061553
index_vybavenosti,0.083859,0.405231,0.002748,1.000000,-0.305097,-0.140217,-0.009062,0.172348,0.151650,0.435386,0.038900
index_socioekonomicky,0.039504,-0.299652,0.011855,-0.305097,1.000000,0.325973,0.239118,-0.302843,-0.115782,-0.026794,-0.000714
index_stari,-0.008985,-0.119885,0.010709,-0.140217,0.325973,1.000000,0.780667,-0.754254,-0.163373,-0.171861,-0.010448
index_zavisloti,-0.038852,-0.054756,0.010960,-0.009062,0.239118,0.780667,1.000000,-0.237695,0.457573,-0.015429,-0.025354
index_zavisloti_2,-0.042118,0.140109,0.031753,0.172348,-0.302843,-0.754254,-0.237695,1.000000,0.754925,0.189061,-0.015282
index_ekonom_zatizeni,-0.064786,0.091288,0.036467,0.151650,-0.115782,-0.163373,0.457573,0.754925,1.000000,0.162614,-0.031108
index_vzdelani,0.092745,0.343186,-0.019820,0.435386,-0.026794,-0.171861,-0.015429,0.189061,0.162614,1.000000,0.092867
kvartal,0.569310,0.067998,0.061553,0.038900,-0.000714,-0.010448,-0.025354,-0.015282,-0.031108,0.092867,1.000000

In [15]:
# 14 - Moravskoslezský kraj
obce_kraj14 = obce_kraje[obce_kraje["VOLKRAJ"] == 14]["KodObec"].tolist()
Motoriste_kraj14 = Motoriste[Motoriste["KodObec"].isin(obce_kraj14)]

Motoriste_kraj14[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.015185,0.203935,0.034704,-0.005848,-0.040121,-0.022293,0.039267,0.019759,0.015342,0.757487
Preferencni_hlasy_celkem_obce,0.015185,1.000000,0.138492,0.281810,-0.714848,-0.095720,-0.081205,0.062390,-0.002424,0.104085,0.041220
podil_preferencnich_z_hlasu,0.203935,0.138492,1.000000,0.043405,-0.163180,-0.000229,-0.031761,0.042429,0.015668,-0.195352,0.322726
index_vybavenosti,0.034704,0.281810,0.043405,1.000000,-0.293663,-0.215770,-0.066173,0.190929,0.127265,0.378526,0.225530
index_socioekonomicky,-0.005848,-0.714848,-0.163180,-0.293663,1.000000,0.229593,0.206287,-0.176509,-0.010462,0.264760,-0.024549
index_stari,-0.040121,-0.095720,-0.000229,-0.215770,0.229593,1.000000,0.790126,-0.763576,-0.120805,0.017731,-0.063145
index_zavisloti,-0.022293,-0.081205,-0.031761,-0.066173,0.206287,0.790126,1.000000,-0.291105,0.470106,0.157938,-0.023872
index_zavisloti_2,0.039267,0.062390,0.042429,0.190929,-0.176509,-0.763576,-0.291105,1.000000,0.707534,0.077231,0.042970
index_ekonom_zatizeni,0.019759,-0.002424,0.015668,0.127265,-0.010462,-0.120805,0.470106,0.707534,1.000000,0.187915,0.022009
index_vzdelani,0.015342,0.104085,-0.195352,0.378526,0.264760,0.017731,0.157938,0.077231,0.187915,1.000000,0.075468
kvartal,0.757487,0.041220,0.322726,0.225530,-0.024549,-0.063145,-0.023872,0.042970,0.022009,0.075468,1.000000