# Korelace podílu prefenčních hlasů pro kandidátky ANO a indexů pro obce v jednotlivých krajích

Korelace indexů s podíly prefenčních hlasů v obcích v daných krajích. Vždy pro každou stranu zvlášť.

In [1]:
import pandas as pd

# obce_kraje
obce_kraje = pd.read_csv("obce_kraje.csv")
obce_kraje = obce_kraje.rename(columns={"OBEC_PREZ": "KodObec"})

#výsledky voleb - okrsky pro dopočítání celkového počtu hlasů pro stranu za obec
vysledky = pd.read_csv("2025_ps_vysledky_okrsky.csv")
vysledky = vysledky.rename(columns={"OBEC": "KodObec"})
hlasy_strany = vysledky.groupby(["KodObec", "KSTRANA"])["POC_HLASU"].sum().reset_index()
hlasy_strany = hlasy_strany.rename(columns={"POC_HLASU": "hlasy_strany_celkem"})
#hlasy_strany.to_csv("hlasy_strany_obce.csv")

In [ ]:
# ANO - kandidátky s aspoň jednou ženou

strany_s_kandidatkami = pd.read_csv("strany_s_kandidatkami_obec.csv")
ANO = strany_s_kandidatkami[strany_s_kandidatkami["KSTRANA"] == 22]

# merge s celkovým počtem hlasů pro stranu + výpočet podílu preferenčních hlasů
ANO = ANO.merge(hlasy_strany, on=["KodObec", "KSTRANA"], how="left")
ANO["podil_preferencnich_z_hlasu"] = ANO["Preferencni_hlasy_celkem_obce"] / ANO["hlasy_strany_celkem"]

PearsonRResult(statistic=np.float64(0.06879409978989848), pvalue=np.float64(5.158583527665084e-08))

In [3]:
# 2 - Středočeský kraj
obce_kraj2 = obce_kraje[obce_kraje["VOLKRAJ"] == 2]["KodObec"].tolist()
ANO_kraj2 = ANO[ANO["KodObec"].isin(obce_kraj2)]

ANO_kraj2[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.012323,0.058909,0.137309,0.020138,0.029271,0.085524,-0.001174,0.051108,0.134152,0.802322
Preferencni_hlasy_celkem_obce,0.012323,1.000000,0.107764,0.436467,-0.259263,-0.020224,-0.020114,-0.000444,-0.012717,0.150888,0.010362
podil_preferencnich_z_hlasu,0.058909,0.107764,1.000000,-0.040281,-0.012556,-0.014534,-0.011686,0.047964,0.039250,0.011420,0.144673
index_vybavenosti,0.137309,0.436467,-0.040281,1.000000,-0.074112,0.159796,0.184702,-0.169124,-0.050743,0.303487,0.145039
index_socioekonomicky,0.020138,-0.259263,-0.012556,-0.074112,1.000000,0.507047,0.390685,-0.308968,-0.060168,0.390181,0.022502
index_stari,0.029271,-0.020224,-0.014534,0.159796,0.507047,1.000000,0.643111,-0.704226,-0.288247,0.108192,0.034994
index_zavisloti,0.085524,-0.020114,-0.011686,0.184702,0.390685,0.643111,1.000000,-0.261121,0.358313,0.201792,0.090856
index_zavisloti_2,-0.001174,-0.000444,0.047964,-0.169124,-0.308968,-0.704226,-0.261121,1.000000,0.807648,0.013435,-0.023361
index_ekonom_zatizeni,0.051108,-0.012717,0.039250,-0.050743,-0.060168,-0.288247,0.358313,0.807648,1.000000,0.136260,0.032906
index_vzdelani,0.134152,0.150888,0.011420,0.303487,0.390181,0.108192,0.201792,0.013435,0.136260,1.000000,0.110672
kvartal,0.802322,0.010362,0.144673,0.145039,0.022502,0.034994,0.090856,-0.023361,0.032906,0.110672,1.000000

In [4]:
# 3 - Jihočeský kraj
obce_kraj3 = obce_kraje[obce_kraje["VOLKRAJ"] == 3]["KodObec"].tolist()
ANO_kraj3 = ANO[ANO["KodObec"].isin(obce_kraj3)]

ANO_kraj3[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.020385,0.111681,0.141080,0.018820,0.021334,0.033607,-0.047282,-0.024179,-0.006373,0.792301
Preferencni_hlasy_celkem_obce,0.020385,1.000000,0.095987,0.415323,-0.246205,-0.045688,-0.013382,0.016183,0.007229,0.186130,0.087096
podil_preferencnich_z_hlasu,0.111681,0.095987,1.000000,0.081146,-0.029104,-0.039468,-0.049871,0.019662,-0.009939,0.031998,0.253557
index_vybavenosti,0.141080,0.415323,0.081146,1.000000,-0.287381,-0.007731,0.000265,-0.115723,-0.104845,0.164520,0.294737
index_socioekonomicky,0.018820,-0.246205,-0.029104,-0.287381,1.000000,0.320323,0.265043,-0.206817,-0.040015,0.259428,-0.009829
index_stari,0.021334,-0.045688,-0.039468,-0.007731,0.320323,1.000000,0.683573,-0.686375,-0.241989,0.010238,0.004835
index_zavisloti,0.033607,-0.013382,-0.049871,0.000265,0.265043,0.683573,1.000000,-0.131973,0.437252,0.138984,0.035852
index_zavisloti_2,-0.047282,0.016183,0.019662,-0.115723,-0.206817,-0.686375,-0.131973,1.000000,0.833768,0.088740,-0.061444
index_ekonom_zatizeni,-0.024179,0.007229,-0.009939,-0.104845,-0.040015,-0.241989,0.437252,0.833768,1.000000,0.157993,-0.035778
index_vzdelani,-0.006373,0.186130,0.031998,0.164520,0.259428,0.010238,0.138984,0.088740,0.157993,1.000000,0.039007
kvartal,0.792301,0.087096,0.253557,0.294737,-0.009829,0.004835,0.035852,-0.061444,-0.035778,0.039007,1.000000

In [5]:
# 4 - Plzeňský kraj
obce_kraj4 = obce_kraje[obce_kraje["VOLKRAJ"] == 4]["KodObec"].tolist()
ANO_kraj4 = ANO[ANO["KodObec"].isin(obce_kraj4)]

ANO_kraj4[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.008687,0.134512,0.106315,-0.049964,-0.004520,-0.022914,-0.036193,-0.046923,-0.092067,0.713395
Preferencni_hlasy_celkem_obce,0.008687,1.000000,0.170864,0.266737,-0.154023,-0.017944,-0.028409,-0.025211,-0.038733,0.112122,0.058047
podil_preferencnich_z_hlasu,0.134512,0.170864,1.000000,0.051911,0.044516,-0.023692,-0.093607,0.036447,-0.009439,0.033857,0.277352
index_vybavenosti,0.106315,0.266737,0.051911,1.000000,-0.216361,-0.011985,-0.009855,-0.144265,-0.147446,0.131479,0.311365
index_socioekonomicky,-0.049964,-0.154023,0.044516,-0.216361,1.000000,0.194483,0.136905,-0.085955,-0.018479,0.232904,-0.074581
index_stari,-0.004520,-0.017944,-0.023692,-0.011985,0.194483,1.000000,0.671524,-0.674980,-0.341184,-0.248305,0.045119
index_zavisloti,-0.022914,-0.028409,-0.093607,-0.009855,0.136905,0.671524,1.000000,-0.222605,0.265745,-0.049535,0.063360
index_zavisloti_2,-0.036193,-0.025211,0.036447,-0.144265,-0.085955,-0.674980,-0.222605,1.000000,0.880698,0.290533,-0.101920
index_ekonom_zatizeni,-0.046923,-0.038733,-0.009439,-0.147446,-0.018479,-0.341184,0.265745,0.880698,1.000000,0.263227,-0.070000
index_vzdelani,-0.092067,0.112122,0.033857,0.131479,0.232904,-0.248305,-0.049535,0.290533,0.263227,1.000000,-0.062255
kvartal,0.713395,0.058047,0.277352,0.311365,-0.074581,0.045119,0.063360,-0.101920,-0.070000,-0.062255,1.000000

In [6]:
# 5 - Karlovarský kraj
obce_kraj5 = obce_kraje[obce_kraje["VOLKRAJ"] == 5]["KodObec"].tolist()
ANO_kraj5 = ANO[ANO["KodObec"].isin(obce_kraj5)]

ANO_kraj5[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.083150,0.251672,0.092141,-0.177574,0.016725,0.015800,0.032106,0.038598,-0.002577,0.705834
Preferencni_hlasy_celkem_obce,0.083150,1.000000,0.157551,0.599275,-0.462023,-0.152539,-0.056275,0.195896,0.151118,0.206236,0.057891
podil_preferencnich_z_hlasu,0.251672,0.157551,1.000000,0.015929,-0.125799,-0.056701,0.001369,0.060939,0.057442,0.050723,0.124611
index_vybavenosti,0.092141,0.599275,0.015929,1.000000,-0.618620,-0.216486,-0.025961,0.257557,0.225229,0.156888,0.133049
index_socioekonomicky,-0.177574,-0.462023,-0.125799,-0.618620,1.000000,-0.012980,-0.101386,-0.108478,-0.156943,0.362101,-0.116965
index_stari,0.016725,-0.152539,-0.056701,-0.216486,-0.012980,1.000000,0.656262,-0.726865,-0.313404,-0.274341,0.094949
index_zavisloti,0.015800,-0.056275,0.001369,-0.025961,-0.101386,0.656262,1.000000,-0.166058,0.398244,-0.087961,0.150980
index_zavisloti_2,0.032106,0.195896,0.060939,0.257557,-0.108478,-0.726865,-0.166058,1.000000,0.838413,0.231806,0.000455
index_ekonom_zatizeni,0.038598,0.151118,0.057442,0.225229,-0.156943,-0.313404,0.398244,0.838413,1.000000,0.165432,0.083871
index_vzdelani,-0.002577,0.206236,0.050723,0.156888,0.362101,-0.274341,-0.087961,0.231806,0.165432,1.000000,0.065203
kvartal,0.705834,0.057891,0.124611,0.133049,-0.116965,0.094949,0.150980,0.000455,0.083871,0.065203,1.000000

In [7]:
# 6 - Ústecký kraj
obce_kraj6 = obce_kraje[obce_kraje["VOLKRAJ"] == 6]["KodObec"].tolist()
ANO_kraj6 = ANO[ANO["KodObec"].isin(obce_kraj6)]

ANO_kraj6[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.086103,-0.015580,0.079306,-0.066958,0.103690,-0.112788,-0.191246,-0.231941,-0.154796,0.811791
Preferencni_hlasy_celkem_obce,0.086103,1.000000,0.184035,0.495275,-0.559885,-0.060614,0.004370,0.045241,0.042789,0.109170,0.071203
podil_preferencnich_z_hlasu,-0.015580,0.184035,1.000000,0.098337,-0.114162,-0.116136,-0.089005,0.073828,0.017777,0.048594,0.053002
index_vybavenosti,0.079306,0.495275,0.098337,1.000000,-0.604858,-0.090612,0.021004,0.052416,0.058205,0.004234,0.122178
index_socioekonomicky,-0.066958,-0.559885,-0.114162,-0.604858,1.000000,-0.004625,-0.066111,-0.028067,-0.060869,0.342421,-0.055648
index_stari,0.103690,-0.060614,-0.116136,-0.090612,-0.004625,1.000000,0.647273,-0.722795,-0.295402,-0.287662,0.089564
index_zavisloti,-0.112788,0.004370,-0.089005,0.021004,-0.066111,0.647273,1.000000,-0.094523,0.456923,-0.070682,-0.083057
index_zavisloti_2,-0.191246,0.045241,0.073828,0.052416,-0.028067,-0.722795,-0.094523,1.000000,0.842334,0.341310,-0.168111
index_ekonom_zatizeni,-0.231941,0.042789,0.017777,0.058205,-0.060869,-0.295402,0.456923,0.842334,1.000000,0.266697,-0.195173
index_vzdelani,-0.154796,0.109170,0.048594,0.004234,0.342421,-0.287662,-0.070682,0.341310,0.266697,1.000000,-0.128228
kvartal,0.811791,0.071203,0.053002,0.122178,-0.055648,0.089564,-0.083057,-0.168111,-0.195173,-0.128228,1.000000

In [8]:
# 7 - Liberecký kraj
obce_kraj7 = obce_kraje[obce_kraje["VOLKRAJ"] == 7]["KodObec"].tolist()
ANO_kraj7 = ANO[ANO["KodObec"].isin(obce_kraj7)]

ANO_kraj7[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.070101,0.125767,0.119317,-0.149766,0.025461,-0.196613,-0.126918,-0.226162,-0.328719,0.830370
Preferencni_hlasy_celkem_obce,0.070101,1.000000,0.229824,0.402523,-0.377975,-0.042445,-0.041297,-0.008432,-0.030474,0.088139,0.107949
podil_preferencnich_z_hlasu,0.125767,0.229824,1.000000,0.032626,-0.121555,0.066450,-0.062536,-0.100296,-0.127939,-0.182422,0.160467
index_vybavenosti,0.119317,0.402523,0.032626,1.000000,-0.466579,-0.096433,-0.033404,0.008578,-0.010263,0.046042,0.226542
index_socioekonomicky,-0.149766,-0.377975,-0.121555,-0.466579,1.000000,0.221101,0.187048,-0.129322,-0.018483,0.463357,-0.121551
index_stari,0.025461,-0.042445,0.066450,-0.096433,0.221101,1.000000,0.634322,-0.760614,-0.363581,-0.000746,0.084532
index_zavisloti,-0.196613,-0.041297,-0.062536,-0.033404,0.187048,0.634322,1.000000,-0.168561,0.389672,0.243425,-0.108596
index_zavisloti_2,-0.126918,-0.008432,-0.100296,0.008578,-0.129322,-0.760614,-0.168561,1.000000,0.842092,0.171344,-0.168085
index_ekonom_zatizeni,-0.226162,-0.030474,-0.127939,-0.010263,-0.018483,-0.363581,0.389672,0.842092,1.000000,0.293284,-0.216465
index_vzdelani,-0.328719,0.088139,-0.182422,0.046042,0.463357,-0.000746,0.243425,0.171344,0.293284,1.000000,-0.230012
kvartal,0.830370,0.107949,0.160467,0.226542,-0.121551,0.084532,-0.108596,-0.168085,-0.216465,-0.230012,1.000000

In [9]:
# 8 - Královéhradecký kraj
obce_kraj8 = obce_kraje[obce_kraje["VOLKRAJ"] == 8]["KodObec"].tolist()
ANO_kraj8 = ANO[ANO["KodObec"].isin(obce_kraj8)]

ANO_kraj8[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.027576,0.030487,-0.010424,0.020340,0.003749,0.014124,-0.006915,0.002825,-0.001307,0.743090
Preferencni_hlasy_celkem_obce,-0.027576,1.000000,0.099594,0.378744,-0.307761,-0.107348,-0.038726,0.118616,0.074952,0.192960,0.029792
podil_preferencnich_z_hlasu,0.030487,0.099594,1.000000,0.005887,0.018059,0.007164,-0.026460,-0.007535,-0.022293,-0.029440,0.150761
index_vybavenosti,-0.010424,0.378744,0.005887,1.000000,-0.372136,-0.187323,-0.075932,0.149675,0.078171,0.209028,0.069056
index_socioekonomicky,0.020340,-0.307761,0.018059,-0.372136,1.000000,0.292616,0.149644,-0.271345,-0.134448,0.248806,-0.005741
index_stari,0.003749,-0.107348,0.007164,-0.187323,0.292616,1.000000,0.673422,-0.717373,-0.187041,-0.008743,0.012591
index_zavisloti,0.014124,-0.038726,-0.026460,-0.075932,0.149644,0.673422,1.000000,-0.055753,0.559957,0.059301,0.002622
index_zavisloti_2,-0.006915,0.118616,-0.007535,0.149675,-0.271345,-0.717373,-0.055753,1.000000,0.796013,0.075692,-0.028731
index_ekonom_zatizeni,0.002825,0.074952,-0.022293,0.078171,-0.134448,-0.187041,0.559957,0.796013,1.000000,0.098760,-0.022252
index_vzdelani,-0.001307,0.192960,-0.029440,0.209028,0.248806,-0.008743,0.059301,0.075692,0.098760,1.000000,0.050806
kvartal,0.743090,0.029792,0.150761,0.069056,-0.005741,0.012591,0.002622,-0.028731,-0.022252,0.050806,1.000000

In [10]:
# 9 - Pardubický kraj
obce_kraj9 = obce_kraje[obce_kraje["VOLKRAJ"] == 9]["KodObec"].tolist()
ANO_kraj9 = ANO[ANO["KodObec"].isin(obce_kraj9)]

ANO_kraj9[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.018031,0.004612,-0.019205,0.054422,0.127762,0.059918,-0.170933,-0.120938,-0.016532,0.801155
Preferencni_hlasy_celkem_obce,-0.018031,1.000000,0.209940,0.372752,-0.260873,-0.063918,-0.029458,0.039218,0.019025,0.215827,0.049564
podil_preferencnich_z_hlasu,0.004612,0.209940,1.000000,0.013115,-0.040411,0.042601,0.016175,-0.051401,-0.037388,0.063224,0.120036
index_vybavenosti,-0.019205,0.372752,0.013115,1.000000,-0.163903,-0.004252,0.036439,-0.064860,-0.038282,0.267569,0.048819
index_socioekonomicky,0.054422,-0.260873,-0.040411,-0.163903,1.000000,0.347286,0.225481,-0.259064,-0.108527,0.335208,0.072199
index_stari,0.127762,-0.063918,0.042601,-0.004252,0.347286,1.000000,0.603603,-0.747958,-0.339646,0.000198,0.138592
index_zavisloti,0.059918,-0.029458,0.016175,0.036439,0.225481,0.603603,1.000000,-0.121852,0.445252,0.111878,0.077806
index_zavisloti_2,-0.170933,0.039218,-0.051401,-0.064860,-0.259064,-0.747958,-0.121852,1.000000,0.834478,0.150755,-0.188037
index_ekonom_zatizeni,-0.120938,0.019025,-0.037388,-0.038282,-0.108527,-0.339646,0.445252,0.834478,1.000000,0.198113,-0.126437
index_vzdelani,-0.016532,0.215827,0.063224,0.267569,0.335208,0.000198,0.111878,0.150755,0.198113,1.000000,-0.023926
kvartal,0.801155,0.049564,0.120036,0.048819,0.072199,0.138592,0.077806,-0.188037,-0.126437,-0.023926,1.000000

In [11]:
# 10 - Kraj Vysočina
obce_kraj10 = obce_kraje[obce_kraje["VOLKRAJ"] == 10]["KodObec"].tolist()
ANO_kraj10 = ANO[ANO["KodObec"].isin(obce_kraj10)]

ANO_kraj10[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.003485,0.059877,0.044834,-0.052658,0.034746,-0.004190,-0.003053,-0.005071,-0.131743,0.786363
Preferencni_hlasy_celkem_obce,0.003485,1.000000,0.081233,0.437304,-0.146582,-0.069440,-0.045812,0.019349,-0.008261,0.210237,0.033515
podil_preferencnich_z_hlasu,0.059877,0.081233,1.000000,-0.023567,0.045115,-0.041532,-0.073988,0.125337,0.070857,0.060879,0.239554
index_vybavenosti,0.044834,0.437304,-0.023567,1.000000,-0.014360,-0.063366,-0.034979,-0.057300,-0.070806,0.276364,0.151949
index_socioekonomicky,-0.052658,-0.146582,0.045115,-0.014360,1.000000,0.213823,0.194152,-0.096740,0.021822,0.251553,0.025059
index_stari,0.034746,-0.069440,-0.041532,-0.063366,0.213823,1.000000,0.687834,-0.623754,-0.174181,-0.012462,-0.003742
index_zavisloti,-0.004190,-0.045812,-0.073988,-0.034979,0.194152,0.687834,1.000000,-0.112607,0.457519,0.173746,-0.035651
index_zavisloti_2,-0.003053,0.019349,0.125337,-0.057300,-0.096740,-0.623754,-0.112607,1.000000,0.832024,0.119979,0.007963
index_ekonom_zatizeni,-0.005071,-0.008261,0.070857,-0.070806,0.021822,-0.174181,0.457519,0.832024,1.000000,0.204369,-0.012778
index_vzdelani,-0.131743,0.210237,0.060879,0.276364,0.251553,-0.012462,0.173746,0.119979,0.204369,1.000000,-0.069924
kvartal,0.786363,0.033515,0.239554,0.151949,0.025059,-0.003742,-0.035651,0.007963,-0.012778,-0.069924,1.000000

In [17]:
# 11 - Jihomoravský kraj
obce_kraj11 = obce_kraje[obce_kraje["VOLKRAJ"] == 11]["KodObec"].tolist()
ANO_kraj11 = ANO[ANO["KodObec"].isin(obce_kraj11)]

ANO_kraj11[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.011572,-0.185778,-0.036268,0.189753,0.108000,0.127909,-0.066003,0.024845,0.327264,0.427372
Preferencni_hlasy_celkem_obce,-0.011572,1.000000,0.165759,0.202727,-0.428606,-0.037863,-0.032303,0.010341,-0.012245,0.150253,0.015142
podil_preferencnich_z_hlasu,-0.185778,0.165759,1.000000,-0.006638,-0.061135,0.008007,-0.031394,-0.009753,-0.030590,-0.030775,0.133664
index_vybavenosti,-0.036268,0.202727,-0.006638,1.000000,-0.054518,-0.014971,0.034160,-0.054009,-0.027697,0.323122,0.147952
index_socioekonomicky,0.189753,-0.428606,-0.061135,-0.054518,1.000000,0.420173,0.415412,-0.239297,0.057157,0.307592,0.087054
index_stari,0.108000,-0.037863,0.008007,-0.014971,0.420173,1.000000,0.744185,-0.732458,-0.184268,0.060653,0.067327
index_zavisloti,0.127909,-0.032303,-0.031394,0.034160,0.415412,0.744185,1.000000,-0.275767,0.420957,0.200271,0.006694
index_zavisloti_2,-0.066003,0.010341,-0.009753,-0.054009,-0.239297,-0.732458,-0.275767,1.000000,0.755822,0.096026,-0.108525
index_ekonom_zatizeni,0.024845,-0.012245,-0.030590,-0.027697,0.057157,-0.184268,0.420957,0.755822,1.000000,0.227040,-0.097852
index_vzdelani,0.327264,0.150253,-0.030775,0.323122,0.307592,0.060653,0.200271,0.096026,0.227040,1.000000,0.105185
kvartal,0.427372,0.015142,0.133664,0.147952,0.087054,0.067327,0.006694,-0.108525,-0.097852,0.105185,1.000000

In [13]:
# 12 - Olomoucký kraj
obce_kraj12 = obce_kraje[obce_kraje["VOLKRAJ"] == 12]["KodObec"].tolist()
ANO_kraj12 = ANO[ANO["KodObec"].isin(obce_kraj12)]

ANO_kraj12[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.016249,0.135894,0.013766,-0.176017,0.028696,0.012113,0.039574,0.042514,-0.105684,0.747708
Preferencni_hlasy_celkem_obce,-0.016249,1.000000,0.175256,0.379480,-0.341501,-0.086392,-0.037527,0.061054,0.037586,0.245506,0.018064
podil_preferencnich_z_hlasu,0.135894,0.175256,1.000000,0.029267,-0.150570,-0.000866,0.064987,0.038974,0.068301,0.059564,0.145393
index_vybavenosti,0.013766,0.379480,0.029267,1.000000,-0.300759,-0.096472,-0.035322,0.019465,0.000347,0.230082,0.192206
index_socioekonomicky,-0.176017,-0.341501,-0.150570,-0.300759,1.000000,0.323704,0.246331,-0.232677,-0.091772,0.356509,-0.192008
index_stari,0.028696,-0.086392,-0.000866,-0.096472,0.323704,1.000000,0.712694,-0.589969,-0.188806,0.000650,0.010268
index_zavisloti,0.012113,-0.037527,0.064987,-0.035322,0.246331,0.712694,1.000000,-0.106583,0.399906,0.079725,0.049264
index_zavisloti_2,0.039574,0.061054,0.038974,0.019465,-0.232677,-0.589969,-0.106583,1.000000,0.868712,0.030805,0.058904
index_ekonom_zatizeni,0.042514,0.037586,0.068301,0.000347,-0.091772,-0.188806,0.399906,0.868712,1.000000,0.068342,0.078839
index_vzdelani,-0.105684,0.245506,0.059564,0.230082,0.356509,0.000650,0.079725,0.030805,0.068342,1.000000,-0.048785
kvartal,0.747708,0.018064,0.145393,0.192206,-0.192008,0.010268,0.049264,0.058904,0.078839,-0.048785,1.000000

In [14]:
# 13 - Zlínský kraj
obce_kraj13 = obce_kraje[obce_kraje["VOLKRAJ"] == 13]["KodObec"].tolist()
ANO_kraj13 = ANO[ANO["KodObec"].isin(obce_kraj13)]

ANO_kraj13[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.044970,0.013047,-0.058686,0.122138,-0.044232,-0.105684,0.016053,-0.056658,-0.118471,0.753983
Preferencni_hlasy_celkem_obce,-0.044970,1.000000,0.234993,0.446424,-0.378108,-0.154588,-0.075396,0.175489,0.109739,0.383002,0.000775
podil_preferencnich_z_hlasu,0.013047,0.234993,1.000000,0.132098,-0.132530,-0.098244,-0.127097,0.029219,-0.059064,0.279219,0.016182
index_vybavenosti,-0.058686,0.446424,0.132098,1.000000,-0.305097,-0.140217,-0.009062,0.172348,0.151650,0.435386,0.079628
index_socioekonomicky,0.122138,-0.378108,-0.132530,-0.305097,1.000000,0.325973,0.239118,-0.302843,-0.115782,-0.026794,0.073668
index_stari,-0.044232,-0.154588,-0.098244,-0.140217,0.325973,1.000000,0.780667,-0.754254,-0.163373,-0.171861,-0.139245
index_zavisloti,-0.105684,-0.075396,-0.127097,-0.009062,0.239118,0.780667,1.000000,-0.237695,0.457573,-0.015429,-0.170151
index_zavisloti_2,0.016053,0.175489,0.029219,0.172348,-0.302843,-0.754254,-0.237695,1.000000,0.754925,0.189061,0.088562
index_ekonom_zatizeni,-0.056658,0.109739,-0.059064,0.151650,-0.115782,-0.163373,0.457573,0.754925,1.000000,0.162614,-0.033809
index_vzdelani,-0.118471,0.383002,0.279219,0.435386,-0.026794,-0.171861,-0.015429,0.189061,0.162614,1.000000,-0.033510
kvartal,0.753983,0.000775,0.016182,0.079628,0.073668,-0.139245,-0.170151,0.088562,-0.033809,-0.033510,1.000000

In [15]:
# 14 - Moravskoslezský kraj
obce_kraj14 = obce_kraje[obce_kraje["VOLKRAJ"] == 14]["KodObec"].tolist()
ANO_kraj14 = ANO[ANO["KodObec"].isin(obce_kraj14)]

ANO_kraj14[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.028487,0.123895,-0.177136,-0.105548,-0.216879,-0.228895,0.147621,-0.032888,-0.186128,0.558832
Preferencni_hlasy_celkem_obce,-0.028487,1.000000,0.193147,0.304133,-0.753316,-0.114316,-0.097815,0.078996,0.000627,0.094182,0.014901
podil_preferencnich_z_hlasu,0.123895,0.193147,1.000000,-0.042688,-0.194480,-0.229797,-0.144754,0.223200,0.098900,-0.076539,0.058246
index_vybavenosti,-0.177136,0.304133,-0.042688,1.000000,-0.293663,-0.215770,-0.066173,0.190929,0.127265,0.378526,-0.008010
index_socioekonomicky,-0.105548,-0.753316,-0.194480,-0.293663,1.000000,0.229593,0.206287,-0.176509,-0.010462,0.264760,-0.046035
index_stari,-0.216879,-0.114316,-0.229797,-0.215770,0.229593,1.000000,0.790126,-0.763576,-0.120805,0.017731,-0.071944
index_zavisloti,-0.228895,-0.097815,-0.144754,-0.066173,0.206287,0.790126,1.000000,-0.291105,0.470106,0.157938,-0.076739
index_zavisloti_2,0.147621,0.078996,0.223200,0.190929,-0.176509,-0.763576,-0.291105,1.000000,0.707534,0.077231,0.049257
index_ekonom_zatizeni,-0.032888,0.000627,0.098900,0.127265,-0.010462,-0.120805,0.470106,0.707534,1.000000,0.187915,-0.011242
index_vzdelani,-0.186128,0.094182,-0.076539,0.378526,0.264760,0.017731,0.157938,0.077231,0.187915,1.000000,0.001606
kvartal,0.558832,0.014901,0.058246,-0.008010,-0.046035,-0.071944,-0.076739,0.049257,-0.011242,0.001606,1.000000