# Korelace podílu prefenčních hlasů pro kandidátky SPD a indexů pro obce v jednotlivých krajích

Korelace indexů s podíly prefenčních hlasů v obcích v daných krajích. Vždy pro každou stranu zvlášť.

In [16]:
import pandas as pd

# obce_kraje
obce_kraje = pd.read_csv("obce_kraje.csv")
obce_kraje = obce_kraje.rename(columns={"OBEC_PREZ": "KodObec"})

# hlasy stran za obec
hlasy_strany = pd.read_csv("hlasy_strany_obce.csv")

In [17]:
# SPD - kandidátky s aspoň jednou ženou

strany_s_kandidatkami = pd.read_csv("strany_s_kandidatkami_obec.csv")
SPD = strany_s_kandidatkami[strany_s_kandidatkami["KSTRANA"] == 6]

# merge s celkovým počtem hlasů pro stranu + výpočet podílu preferenčních hlasů
SPD = SPD.merge(hlasy_strany, on=["KodObec", "KSTRANA"], how="left")
SPD["podil_preferencnich_z_hlasu"] = SPD["Preferencni_hlasy_celkem_obce"] / SPD["hlasy_strany_celkem"]

In [18]:
# 2 - Středočeský kraj
obce_kraj2 = obce_kraje[obce_kraje["VOLKRAJ"] == 2]["KodObec"].tolist()
SPD_kraj2 = SPD[SPD["KodObec"].isin(obce_kraj2)]

SPD_kraj2[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.067253,0.289039,0.110617,-0.056404,0.013659,-0.015867,-0.083933,-0.090855,-0.045222,0.775817
Preferencni_hlasy_celkem_obce,0.067253,1.000000,0.106131,0.441694,-0.262014,-0.010876,-0.015211,-0.012233,-0.021082,0.151479,0.156055
podil_preferencnich_z_hlasu,0.289039,0.106131,1.000000,0.005089,-0.056273,0.003857,-0.041958,-0.051199,-0.075043,0.003158,0.333938
index_vybavenosti,0.110617,0.441694,0.005089,1.000000,-0.077685,0.155236,0.180696,-0.164371,-0.049198,0.301417,0.293164
index_socioekonomicky,-0.056404,-0.262014,-0.056273,-0.077685,1.000000,0.507280,0.391556,-0.312392,-0.064240,0.386854,-0.086913
index_stari,0.013659,-0.010876,0.003857,0.155236,0.507280,1.000000,0.645367,-0.705746,-0.290546,0.105684,0.030684
index_zavisloti,-0.015867,-0.015211,-0.041958,0.180696,0.391556,0.645367,1.000000,-0.259853,0.356450,0.197799,0.001761
index_zavisloti_2,-0.083933,-0.012233,-0.051199,-0.164371,-0.312392,-0.705746,-0.259853,1.000000,0.809594,0.016034,-0.115024
index_ekonom_zatizeni,-0.090855,-0.021082,-0.075043,-0.049198,-0.064240,-0.290546,0.356450,0.809594,1.000000,0.135750,-0.110221
index_vzdelani,-0.045222,0.151479,0.003158,0.301417,0.386854,0.105684,0.197799,0.016034,0.135750,1.000000,0.016227
kvartal,0.775817,0.156055,0.333938,0.293164,-0.086913,0.030684,0.001761,-0.115024,-0.110221,0.016227,1.000000

In [19]:
# 3 - Jihočeský kraj
obce_kraj3 = obce_kraje[obce_kraje["VOLKRAJ"] == 3]["KodObec"].tolist()
SPD_kraj3 = SPD[SPD["KodObec"].isin(obce_kraj3)]

SPD_kraj3[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.079704,0.417205,0.230037,0.013924,0.005721,0.041871,-0.011457,0.014415,0.085149,0.830997
Preferencni_hlasy_celkem_obce,0.079704,1.000000,0.089770,0.396424,-0.234439,-0.039217,-0.008567,0.016201,0.009599,0.193547,0.127709
podil_preferencnich_z_hlasu,0.417205,0.089770,1.000000,0.080318,0.107334,0.090023,0.099777,-0.071201,-0.005402,0.048738,0.470609
index_vybavenosti,0.230037,0.396424,0.080318,1.000000,-0.310312,-0.016575,0.007219,-0.084868,-0.072580,0.174111,0.373805
index_socioekonomicky,0.013924,-0.234439,0.107334,-0.310312,1.000000,0.323816,0.276726,-0.212741,-0.028811,0.267292,-0.071800
index_stari,0.005721,-0.039217,0.090023,-0.016575,0.323816,1.000000,0.689479,-0.719091,-0.242967,0.006684,0.010858
index_zavisloti,0.041871,-0.008567,0.099777,0.007219,0.276726,0.689479,1.000000,-0.159084,0.448004,0.150998,0.056514
index_zavisloti_2,-0.011457,0.016201,-0.071201,-0.084868,-0.212741,-0.719091,-0.159084,1.000000,0.811376,0.128484,-0.032243
index_ekonom_zatizeni,0.014415,0.009599,-0.005402,-0.072580,-0.028811,-0.242967,0.448004,0.811376,1.000000,0.205829,0.004262
index_vzdelani,0.085149,0.193547,0.048738,0.174111,0.267292,0.006684,0.150998,0.128484,0.205829,1.000000,0.123020
kvartal,0.830997,0.127709,0.470609,0.373805,-0.071800,0.010858,0.056514,-0.032243,0.004262,0.123020,1.000000

In [20]:
# 4 - Plzeňský kraj
obce_kraj4 = obce_kraje[obce_kraje["VOLKRAJ"] == 4]["KodObec"].tolist()
SPD_kraj4 = SPD[SPD["KodObec"].isin(obce_kraj4)]

SPD_kraj4[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.061725,0.342909,0.299673,-0.010363,0.052743,0.030872,-0.129713,-0.113214,-0.003706,0.859201
Preferencni_hlasy_celkem_obce,0.061725,1.000000,0.152905,0.289402,-0.164006,-0.019366,-0.032182,-0.029590,-0.044802,0.112641,0.120123
podil_preferencnich_z_hlasu,0.342909,0.152905,1.000000,0.042109,0.058808,0.060712,-0.004539,-0.086785,-0.087946,-0.056875,0.443849
index_vybavenosti,0.299673,0.289402,0.042109,1.000000,-0.221918,-0.018117,-0.018418,-0.143222,-0.150406,0.132521,0.482511
index_socioekonomicky,-0.010363,-0.164006,0.058808,-0.221918,1.000000,0.196599,0.138512,-0.087720,-0.019653,0.236952,-0.067855
index_stari,0.052743,-0.019366,0.060712,-0.018117,0.196599,1.000000,0.669182,-0.674515,-0.342643,-0.250850,0.051344
index_zavisloti,0.030872,-0.032182,-0.004539,-0.018418,0.138512,0.669182,1.000000,-0.219770,0.266663,-0.050738,0.019289
index_zavisloti_2,-0.129713,-0.029590,-0.086785,-0.143222,-0.087720,-0.674515,-0.219770,1.000000,0.881622,0.291963,-0.160692
index_ekonom_zatizeni,-0.113214,-0.044802,-0.087946,-0.150406,-0.019653,-0.342643,0.266663,0.881622,1.000000,0.263896,-0.149423
index_vzdelani,-0.003706,0.112641,-0.056875,0.132521,0.236952,-0.250850,-0.050738,0.291963,0.263896,1.000000,0.028454
kvartal,0.859201,0.120123,0.443849,0.482511,-0.067855,0.051344,0.019289,-0.160692,-0.149423,0.028454,1.000000

In [21]:
# 5 - Karlovarský kraj
obce_kraj5 = obce_kraje[obce_kraje["VOLKRAJ"] == 5]["KodObec"].tolist()
SPD_kraj5 = SPD[SPD["KodObec"].isin(obce_kraj5)]

SPD_kraj5[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.002537,0.017908,-0.012839,-0.029338,0.107652,0.031161,-0.184891,-0.154762,0.006880,0.724659
Preferencni_hlasy_celkem_obce,0.002537,1.000000,0.138062,0.555466,-0.395728,-0.147914,-0.074173,0.178643,0.125177,0.213716,0.096509
podil_preferencnich_z_hlasu,0.017908,0.138062,1.000000,0.028437,-0.087288,0.167675,0.050868,-0.205508,-0.163047,0.055536,0.358353
index_vybavenosti,-0.012839,0.555466,0.028437,1.000000,-0.618620,-0.216486,-0.025961,0.257557,0.225229,0.156888,0.173488
index_socioekonomicky,-0.029338,-0.395728,-0.087288,-0.618620,1.000000,-0.012980,-0.101386,-0.108478,-0.156943,0.362101,-0.173390
index_stari,0.107652,-0.147914,0.167675,-0.216486,-0.012980,1.000000,0.656262,-0.726865,-0.313404,-0.274341,0.154150
index_zavisloti,0.031161,-0.074173,0.050868,-0.025961,-0.101386,0.656262,1.000000,-0.166058,0.398244,-0.087961,0.116311
index_zavisloti_2,-0.184891,0.178643,-0.205508,0.257557,-0.108478,-0.726865,-0.166058,1.000000,0.838413,0.231806,-0.193999
index_ekonom_zatizeni,-0.154762,0.125177,-0.163047,0.225229,-0.156943,-0.313404,0.398244,0.838413,1.000000,0.165432,-0.116171
index_vzdelani,0.006880,0.213716,0.055536,0.156888,0.362101,-0.274341,-0.087961,0.231806,0.165432,1.000000,0.070266
kvartal,0.724659,0.096509,0.358353,0.173488,-0.173390,0.154150,0.116311,-0.193999,-0.116171,0.070266,1.000000

In [22]:
# 6 - Ústecký kraj
obce_kraj6 = obce_kraje[obce_kraje["VOLKRAJ"] == 6]["KodObec"].tolist()
SPD_kraj6 = SPD[SPD["KodObec"].isin(obce_kraj6)]

SPD_kraj6[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.052448,0.164068,0.041262,-0.151094,0.144616,0.020401,-0.126797,-0.103987,-0.163111,0.778442
Preferencni_hlasy_celkem_obce,0.052448,1.000000,0.112014,0.506390,-0.549620,-0.064607,0.001834,0.048318,0.044856,0.119815,0.122940
podil_preferencnich_z_hlasu,0.164068,0.112014,1.000000,0.006768,-0.025053,0.078764,0.075687,-0.035779,0.008723,0.013415,0.285512
index_vybavenosti,0.041262,0.506390,0.006768,1.000000,-0.607971,-0.100825,-0.000851,0.043125,0.038680,0.018249,0.235974
index_socioekonomicky,-0.151094,-0.549620,-0.025053,-0.607971,1.000000,-0.003947,-0.064411,-0.026043,-0.058697,0.343370,-0.215506
index_stari,0.144616,-0.064607,0.078764,-0.100825,-0.003947,1.000000,0.649074,-0.736896,-0.315592,-0.283056,0.103886
index_zavisloti,0.020401,0.001834,0.075687,-0.000851,-0.064411,0.649074,1.000000,-0.121583,0.433920,-0.046209,-0.005018
index_zavisloti_2,-0.126797,0.048318,-0.035779,0.043125,-0.026043,-0.736896,-0.121583,1.000000,0.841510,0.364431,-0.114386
index_ekonom_zatizeni,-0.103987,0.044856,0.008723,0.038680,-0.058697,-0.315592,0.433920,0.841510,1.000000,0.305638,-0.106558
index_vzdelani,-0.163111,0.119815,0.013415,0.018249,0.343370,-0.283056,-0.046209,0.364431,0.305638,1.000000,-0.098959
kvartal,0.778442,0.122940,0.285512,0.235974,-0.215506,0.103886,-0.005018,-0.114386,-0.106558,-0.098959,1.000000

In [23]:
# 7 - Liberecký kraj
obce_kraj7 = obce_kraje[obce_kraje["VOLKRAJ"] == 7]["KodObec"].tolist()
SPD_kraj7 = SPD[SPD["KodObec"].isin(obce_kraj7)]

SPD_kraj7[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.006585,0.157376,0.113579,0.026346,-0.002615,0.010065,0.005338,0.010495,0.000485,0.763487
Preferencni_hlasy_celkem_obce,-0.006585,1.000000,0.097080,0.366819,-0.345008,-0.037563,-0.035248,-0.010311,-0.028920,0.100290,0.080108
podil_preferencnich_z_hlasu,0.157376,0.097080,1.000000,-0.069125,-0.082201,0.003430,0.010896,-0.027573,-0.019802,-0.109410,0.264647
index_vybavenosti,0.113579,0.366819,-0.069125,1.000000,-0.466579,-0.096433,-0.033404,0.008578,-0.010263,0.046042,0.305185
index_socioekonomicky,0.026346,-0.345008,-0.082201,-0.466579,1.000000,0.221101,0.187048,-0.129322,-0.018483,0.463357,-0.115557
index_stari,-0.002615,-0.037563,0.003430,-0.096433,0.221101,1.000000,0.634322,-0.760614,-0.363581,-0.000746,0.039874
index_zavisloti,0.010065,-0.035248,0.010896,-0.033404,0.187048,0.634322,1.000000,-0.168561,0.389672,0.243425,0.035981
index_zavisloti_2,0.005338,-0.010311,-0.027573,0.008578,-0.129322,-0.760614,-0.168561,1.000000,0.842092,0.171344,-0.054443
index_ekonom_zatizeni,0.010495,-0.028920,-0.019802,-0.010263,-0.018483,-0.363581,0.389672,0.842092,1.000000,0.293284,-0.031180
index_vzdelani,0.000485,0.100290,-0.109410,0.046042,0.463357,-0.000746,0.243425,0.171344,0.293284,1.000000,-0.019414
kvartal,0.763487,0.080108,0.264647,0.305185,-0.115557,0.039874,0.035981,-0.054443,-0.031180,-0.019414,1.000000

In [24]:
# 8 - Královéhradecký kraj
obce_kraj8 = obce_kraje[obce_kraje["VOLKRAJ"] == 8]["KodObec"].tolist()
SPD_kraj8 = SPD[SPD["KodObec"].isin(obce_kraj8)]

SPD_kraj8[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.067441,0.180663,0.220697,-0.071358,-0.069415,-0.061701,0.018503,-0.023026,-0.025286,0.833512
Preferencni_hlasy_celkem_obce,0.067441,1.000000,0.073799,0.411318,-0.327167,-0.108906,-0.039580,0.122094,0.077576,0.201489,0.155614
podil_preferencnich_z_hlasu,0.180663,0.073799,1.000000,-0.008057,-0.066680,-0.022393,-0.057093,0.025180,-0.014555,-0.032832,0.347214
index_vybavenosti,0.220697,0.411318,-0.008057,1.000000,-0.377227,-0.188631,-0.087915,0.150849,0.071485,0.203692,0.398741
index_socioekonomicky,-0.071358,-0.327167,-0.066680,-0.377227,1.000000,0.297492,0.143343,-0.291927,-0.155069,0.254048,-0.171620
index_stari,-0.069415,-0.108906,-0.022393,-0.188631,0.297492,1.000000,0.692339,-0.721282,-0.171969,-0.006122,-0.080729
index_zavisloti,-0.061701,-0.039580,-0.057093,-0.087915,0.143343,0.692339,1.000000,-0.087784,0.550897,0.051395,-0.050855
index_zavisloti_2,0.018503,0.122094,0.025180,0.150849,-0.291927,-0.721282,-0.087784,1.000000,0.782991,0.070460,0.032131
index_ekonom_zatizeni,-0.023026,0.077576,-0.014555,0.071485,-0.155069,-0.171969,0.550897,0.782991,1.000000,0.091125,-0.004836
index_vzdelani,-0.025286,0.201489,-0.032832,0.203692,0.254048,-0.006122,0.051395,0.070460,0.091125,1.000000,-0.000186
kvartal,0.833512,0.155614,0.347214,0.398741,-0.171620,-0.080729,-0.050855,0.032131,-0.004836,-0.000186,1.000000

In [25]:
# 9 - Pardubický kraj
obce_kraj9 = obce_kraje[obce_kraje["VOLKRAJ"] == 9]["KodObec"].tolist()
SPD_kraj9 = SPD[SPD["KodObec"].isin(obce_kraj9)]

SPD_kraj9[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.041391,0.265677,0.057907,0.096352,0.045160,0.000619,-0.083027,-0.074557,0.107468,0.766028
Preferencni_hlasy_celkem_obce,0.041391,1.000000,0.149270,0.357446,-0.243294,-0.055873,-0.034108,0.021256,0.000240,0.206452,0.125926
podil_preferencnich_z_hlasu,0.265677,0.149270,1.000000,0.004844,-0.021700,0.049164,-0.056669,-0.147050,-0.164114,-0.028296,0.348961
index_vybavenosti,0.057907,0.357446,0.004844,1.000000,-0.163903,-0.004252,0.036439,-0.064860,-0.038282,0.267569,0.219394
index_socioekonomicky,0.096352,-0.243294,-0.021700,-0.163903,1.000000,0.347286,0.225481,-0.259064,-0.108527,0.335208,0.022356
index_stari,0.045160,-0.055873,0.049164,-0.004252,0.347286,1.000000,0.603603,-0.747958,-0.339646,0.000198,0.050797
index_zavisloti,0.000619,-0.034108,-0.056669,0.036439,0.225481,0.603603,1.000000,-0.121852,0.445252,0.111878,-0.005572
index_zavisloti_2,-0.083027,0.021256,-0.147050,-0.064860,-0.259064,-0.747958,-0.121852,1.000000,0.834478,0.150755,-0.102897
index_ekonom_zatizeni,-0.074557,0.000240,-0.164114,-0.038282,-0.108527,-0.339646,0.445252,0.834478,1.000000,0.198113,-0.095920
index_vzdelani,0.107468,0.206452,-0.028296,0.267569,0.335208,0.000198,0.111878,0.150755,0.198113,1.000000,0.140489
kvartal,0.766028,0.125926,0.348961,0.219394,0.022356,0.050797,-0.005572,-0.102897,-0.095920,0.140489,1.000000

In [26]:
# 10 - Kraj Vysočina
obce_kraj10 = obce_kraje[obce_kraje["VOLKRAJ"] == 10]["KodObec"].tolist()
SPD_kraj10 = SPD[SPD["KodObec"].isin(obce_kraj10)]

SPD_kraj10[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.059731,0.353887,0.168663,0.027935,-0.020774,-0.030396,-0.003901,-0.021425,0.080115,0.794922
Preferencni_hlasy_celkem_obce,0.059731,1.000000,0.086551,0.385388,-0.142209,-0.065741,-0.047512,0.027077,-0.005657,0.188441,0.155151
podil_preferencnich_z_hlasu,0.353887,0.086551,1.000000,0.010607,-0.001637,-0.058876,-0.071004,0.046196,-0.003646,0.002423,0.426071
index_vybavenosti,0.168663,0.385388,0.010607,1.000000,-0.005907,-0.077896,-0.050112,-0.029854,-0.054972,0.287508,0.328587
index_socioekonomicky,0.027935,-0.142209,-0.001637,-0.005907,1.000000,0.232064,0.214690,-0.201507,-0.040844,0.244574,-0.025921
index_stari,-0.020774,-0.065741,-0.058876,-0.077896,0.232064,1.000000,0.688452,-0.658032,-0.140922,-0.004940,0.013485
index_zavisloti,-0.030396,-0.047512,-0.071004,-0.050112,0.214690,0.688452,1.000000,-0.060365,0.546549,0.181182,0.003303
index_zavisloti_2,-0.003901,0.027077,0.046196,-0.029854,-0.201507,-0.658032,-0.060365,1.000000,0.802908,0.092131,-0.029021
index_ekonom_zatizeni,-0.021425,-0.005657,-0.003646,-0.054972,-0.040844,-0.140922,0.546549,0.802908,1.000000,0.185495,-0.022375
index_vzdelani,0.080115,0.188441,0.002423,0.287508,0.244574,-0.004940,0.181182,0.092131,0.185495,1.000000,0.096873
kvartal,0.794922,0.155151,0.426071,0.328587,-0.025921,0.013485,0.003303,-0.029021,-0.022375,0.096873,1.000000

In [27]:
# 11 - Jihomoravský kraj
obce_kraj11 = obce_kraje[obce_kraje["VOLKRAJ"] == 11]["KodObec"].tolist()
SPD_kraj11 = SPD[SPD["KodObec"].isin(obce_kraj11)]

SPD_kraj11[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.021855,0.339754,0.192391,-0.046095,-0.005891,-0.009053,-0.048101,-0.052062,-0.073377,0.864995
Preferencni_hlasy_celkem_obce,0.021855,1.000000,0.091326,0.181907,-0.424784,-0.029939,-0.025766,0.006195,-0.011920,0.148154,0.021608
podil_preferencnich_z_hlasu,0.339754,0.091326,1.000000,-0.076028,-0.016826,0.056542,0.106585,0.004624,0.078114,0.072374,0.383626
index_vybavenosti,0.192391,0.181907,-0.076028,1.000000,-0.054208,-0.013662,0.042267,-0.048313,-0.016772,0.329677,0.297023
index_socioekonomicky,-0.046095,-0.424784,-0.016826,-0.054208,1.000000,0.425532,0.427078,-0.245051,0.062026,0.306106,0.000461
index_stari,-0.005891,-0.029939,0.056542,-0.013662,0.425532,1.000000,0.752484,-0.733814,-0.178323,0.053735,0.018774
index_zavisloti,-0.009053,-0.025766,0.106585,0.042267,0.427078,0.752484,1.000000,-0.292292,0.413270,0.206466,0.028872
index_zavisloti_2,-0.048101,0.006195,0.004624,-0.048313,-0.245051,-0.733814,-0.292292,1.000000,0.750046,0.108484,-0.060244
index_ekonom_zatizeni,-0.052062,-0.011920,0.078114,-0.016772,0.062026,-0.178323,0.413270,0.750046,1.000000,0.246088,-0.037396
index_vzdelani,-0.073377,0.148154,0.072374,0.329677,0.306106,0.053735,0.206466,0.108484,0.246088,1.000000,-0.010496
kvartal,0.864995,0.021608,0.383626,0.297023,0.000461,0.018774,0.028872,-0.060244,-0.037396,-0.010496,1.000000

In [28]:
# 12 - Olomoucký kraj
obce_kraj12 = obce_kraje[obce_kraje["VOLKRAJ"] == 12]["KodObec"].tolist()
SPD_kraj12 = SPD[SPD["KodObec"].isin(obce_kraj12)]

SPD_kraj12[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.013565,0.158785,0.085921,0.064509,0.014652,-0.030816,-0.083462,-0.092287,0.072282,0.775443
Preferencni_hlasy_celkem_obce,-0.013565,1.000000,0.122341,0.383841,-0.354095,-0.097300,-0.049645,0.065938,0.036051,0.243625,0.049233
podil_preferencnich_z_hlasu,0.158785,0.122341,1.000000,0.013899,-0.132321,-0.091575,-0.094214,-0.006734,-0.053141,0.003659,0.284682
index_vybavenosti,0.085921,0.383841,0.013899,1.000000,-0.300759,-0.096472,-0.035322,0.019465,0.000347,0.230082,0.249884
index_socioekonomicky,0.064509,-0.354095,-0.132321,-0.300759,1.000000,0.323704,0.246331,-0.232677,-0.091772,0.356509,-0.041038
index_stari,0.014652,-0.097300,-0.091575,-0.096472,0.323704,1.000000,0.712694,-0.589969,-0.188806,0.000650,-0.011065
index_zavisloti,-0.030816,-0.049645,-0.094214,-0.035322,0.246331,0.712694,1.000000,-0.106583,0.399906,0.079725,-0.088911
index_zavisloti_2,-0.083462,0.065938,-0.006734,0.019465,-0.232677,-0.589969,-0.106583,1.000000,0.868712,0.030805,-0.118743
index_ekonom_zatizeni,-0.092287,0.036051,-0.053141,0.000347,-0.091772,-0.188806,0.399906,0.868712,1.000000,0.068342,-0.153750
index_vzdelani,0.072282,0.243625,0.003659,0.230082,0.356509,0.000650,0.079725,0.030805,0.068342,1.000000,0.059351
kvartal,0.775443,0.049233,0.284682,0.249884,-0.041038,-0.011065,-0.088911,-0.118743,-0.153750,0.059351,1.000000

In [29]:
# 13 - Zlínský kraj
obce_kraj13 = obce_kraje[obce_kraje["VOLKRAJ"] == 13]["KodObec"].tolist()
SPD_kraj13 = SPD[SPD["KodObec"].isin(obce_kraj13)]

SPD_kraj13[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.021996,0.230264,0.126243,-0.074400,0.007828,0.021236,0.026181,0.038304,-0.048136,0.816482
Preferencni_hlasy_celkem_obce,0.021996,1.000000,0.129435,0.399378,-0.325875,-0.135308,-0.062355,0.159653,0.104049,0.354708,0.103924
podil_preferencnich_z_hlasu,0.230264,0.129435,1.000000,-0.023174,-0.047143,-0.060787,-0.005328,0.141426,0.125865,0.084501,0.290417
index_vybavenosti,0.126243,0.399378,-0.023174,1.000000,-0.305097,-0.140217,-0.009062,0.172348,0.151650,0.435386,0.314429
index_socioekonomicky,-0.074400,-0.325875,-0.047143,-0.305097,1.000000,0.325973,0.239118,-0.302843,-0.115782,-0.026794,-0.137811
index_stari,0.007828,-0.135308,-0.060787,-0.140217,0.325973,1.000000,0.780667,-0.754254,-0.163373,-0.171861,0.039030
index_zavisloti,0.021236,-0.062355,-0.005328,-0.009062,0.239118,0.780667,1.000000,-0.237695,0.457573,-0.015429,0.043816
index_zavisloti_2,0.026181,0.159653,0.141426,0.172348,-0.302843,-0.754254,-0.237695,1.000000,0.754925,0.189061,0.012547
index_ekonom_zatizeni,0.038304,0.104049,0.125865,0.151650,-0.115782,-0.163373,0.457573,0.754925,1.000000,0.162614,0.041069
index_vzdelani,-0.048136,0.354708,0.084501,0.435386,-0.026794,-0.171861,-0.015429,0.189061,0.162614,1.000000,0.047549
kvartal,0.816482,0.103924,0.290417,0.314429,-0.137811,0.039030,0.043816,0.012547,0.041069,0.047549,1.000000

In [30]:
# 14 - Moravskoslezský kraj
obce_kraj14 = obce_kraje[obce_kraje["VOLKRAJ"] == 14]["KodObec"].tolist()
SPD_kraj14 = SPD[SPD["KodObec"].isin(obce_kraj14)]

SPD_kraj14[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.058694,0.164193,0.215064,0.017548,0.032986,0.057233,-0.029554,0.015329,0.090806,0.742281
Preferencni_hlasy_celkem_obce,0.058694,1.000000,0.145331,0.306922,-0.744447,-0.114057,-0.098820,0.080317,0.001072,0.106695,0.113637
podil_preferencnich_z_hlasu,0.164193,0.145331,1.000000,0.021642,-0.100962,-0.066279,0.064546,0.190390,0.227444,0.045633,0.242539
index_vybavenosti,0.215064,0.306922,0.021642,1.000000,-0.291410,-0.216528,-0.075042,0.184992,0.117411,0.385201,0.391785
index_socioekonomicky,0.017548,-0.744447,-0.100962,-0.291410,1.000000,0.230391,0.216965,-0.170266,0.003357,0.261326,-0.098266
index_stari,0.032986,-0.114057,-0.066279,-0.216528,0.230391,1.000000,0.797255,-0.773119,-0.126322,0.018417,-0.054092
index_zavisloti,0.057233,-0.098820,0.064546,-0.075042,0.216965,0.797255,1.000000,-0.318835,0.453580,0.172315,0.009142
index_zavisloti_2,-0.029554,0.080317,0.190390,0.184992,-0.170266,-0.773119,-0.318835,1.000000,0.700086,0.090940,0.047635
index_ekonom_zatizeni,0.015329,0.001072,0.227444,0.117411,0.003357,-0.126322,0.453580,0.700086,1.000000,0.215328,0.051678
index_vzdelani,0.090806,0.106695,0.045633,0.385201,0.261326,0.018417,0.172315,0.090940,0.215328,1.000000,0.167725
kvartal,0.742281,0.113637,0.242539,0.391785,-0.098266,-0.054092,0.009142,0.047635,0.051678,0.167725,1.000000