# Korelace podílu prefenčních hlasů pro kandidátky Piráti a indexů pro obce v jednotlivých krajích

Korelace indexů s podíly prefenčních hlasů v obcích v daných krajích. Vždy pro každou stranu zvlášť.

In [1]:
import pandas as pd

# obce_kraje
obce_kraje = pd.read_csv("obce_kraje.csv")
obce_kraje = obce_kraje.rename(columns={"OBEC_PREZ": "KodObec"})

# hlasy stran za obec
hlasy_strany = pd.read_csv("hlasy_strany_obce.csv")

In [2]:
# Pirati - kandidátky s aspoň jednou ženou

strany_s_kandidatkami = pd.read_csv("strany_s_kandidatkami_obec.csv")
Pirati = strany_s_kandidatkami[strany_s_kandidatkami["KSTRANA"] == 16]

# merge s celkovým počtem hlasů pro stranu + výpočet podílu preferenčních hlasů
Pirati = Pirati.merge(hlasy_strany, on=["KodObec", "KSTRANA"], how="left")
Pirati["podil_preferencnich_z_hlasu"] = Pirati["Preferencni_hlasy_celkem_obce"] / Pirati["hlasy_strany_celkem"]

In [3]:
# 2 - Středočeský kraj
obce_kraj2 = obce_kraje[obce_kraje["VOLKRAJ"] == 2]["KodObec"].tolist()
Pirati_kraj2 = Pirati[Pirati["KodObec"].isin(obce_kraj2)]

Pirati_kraj2[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.069299,0.317167,0.187436,0.053459,0.091111,0.136296,-0.124491,-0.037918,0.084814,0.818401
Preferencni_hlasy_celkem_obce,0.069299,1.000000,0.102316,0.538779,-0.172361,0.065680,0.064435,-0.067008,-0.025846,0.267541,0.170560
podil_preferencnich_z_hlasu,0.317167,0.102316,1.000000,0.110943,0.009123,0.117586,0.061333,-0.147079,-0.105510,0.049084,0.414879
index_vybavenosti,0.187436,0.538779,0.110943,1.000000,-0.081440,0.154594,0.180130,-0.163865,-0.049468,0.296836,0.374305
index_socioekonomicky,0.053459,-0.172361,0.009123,-0.081440,1.000000,0.504864,0.392270,-0.308530,-0.060792,0.387084,0.049240
index_stari,0.091111,0.065680,0.117586,0.154594,0.504864,1.000000,0.646780,-0.706993,-0.292833,0.102894,0.152443
index_zavisloti,0.136296,0.064435,0.061333,0.180130,0.392270,0.646780,1.000000,-0.265709,0.350907,0.202377,0.154945
index_zavisloti_2,-0.124491,-0.067008,-0.147079,-0.163865,-0.308530,-0.706993,-0.265709,1.000000,0.809510,0.024347,-0.215898
index_ekonom_zatizeni,-0.037918,-0.025846,-0.105510,-0.049468,-0.060792,-0.292833,0.350907,0.809510,1.000000,0.146896,-0.115347
index_vzdelani,0.084814,0.267541,0.049084,0.296836,0.387084,0.102894,0.202377,0.024347,0.146896,1.000000,0.165227
kvartal,0.818401,0.170560,0.414879,0.374305,0.049240,0.152443,0.154945,-0.215898,-0.115347,0.165227,1.000000

In [4]:
# 3 - Jihočeský kraj
obce_kraj3 = obce_kraje[obce_kraje["VOLKRAJ"] == 3]["KodObec"].tolist()
Pirati_kraj3 = Pirati[Pirati["KodObec"].isin(obce_kraj3)]

Pirati_kraj3[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.042663,0.443802,0.239534,-0.045713,0.099034,0.030906,-0.148467,-0.113536,-0.010465,0.838096
Preferencni_hlasy_celkem_obce,0.042663,1.000000,0.052170,0.337499,-0.213275,-0.031537,-0.008230,0.012294,0.006228,0.188711,0.101213
podil_preferencnich_z_hlasu,0.443802,0.052170,1.000000,0.046349,0.052476,0.108796,0.113115,-0.096525,-0.021758,0.011712,0.560204
index_vybavenosti,0.239534,0.337499,0.046349,1.000000,-0.322990,-0.020845,-0.011237,-0.085866,-0.081955,0.160949,0.375512
index_socioekonomicky,-0.045713,-0.213275,0.052476,-0.322990,1.000000,0.336610,0.274304,-0.219221,-0.039673,0.251639,-0.049312
index_stari,0.099034,-0.031537,0.108796,-0.020845,0.336610,1.000000,0.670165,-0.701784,-0.243382,0.020001,0.097170
index_zavisloti,0.030906,-0.008230,0.113115,-0.011237,0.274304,0.670165,1.000000,-0.090975,0.479459,0.163680,0.044385
index_zavisloti_2,-0.148467,0.012294,-0.096525,-0.085866,-0.219221,-0.701784,-0.090975,1.000000,0.830307,0.108325,-0.162792
index_ekonom_zatizeni,-0.113536,0.006228,-0.021758,-0.081955,-0.039673,-0.243382,0.479459,0.830307,1.000000,0.187139,-0.118616
index_vzdelani,-0.010465,0.188711,0.011712,0.160949,0.251639,0.020001,0.163680,0.108325,0.187139,1.000000,0.088458
kvartal,0.838096,0.101213,0.560204,0.375512,-0.049312,0.097170,0.044385,-0.162792,-0.118616,0.088458,1.000000

In [5]:
# 4 - Plzeňský kraj
obce_kraj4 = obce_kraje[obce_kraje["VOLKRAJ"] == 4]["KodObec"].tolist()
Pirati_kraj4 = Pirati[Pirati["KodObec"].isin(obce_kraj4)]

Pirati_kraj4[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.024880,0.380805,0.176436,-0.040072,0.029915,0.053105,-0.023596,0.002962,0.080349,0.817007
Preferencni_hlasy_celkem_obce,0.024880,1.000000,0.085498,0.213574,-0.146133,-0.011593,-0.018671,-0.019916,-0.028942,0.110031,0.052438
podil_preferencnich_z_hlasu,0.380805,0.085498,1.000000,-0.043222,0.000115,0.080241,0.071845,-0.012813,0.022906,0.038690,0.462257
index_vybavenosti,0.176436,0.213574,-0.043222,1.000000,-0.251961,-0.017548,-0.003174,-0.125471,-0.125656,0.135632,0.318476
index_socioekonomicky,-0.040072,-0.146133,0.000115,-0.251961,1.000000,0.232983,0.157887,-0.125869,-0.046295,0.213890,-0.014885
index_stari,0.029915,-0.011593,0.080241,-0.017548,0.232983,1.000000,0.672205,-0.677204,-0.336859,-0.241072,0.084287
index_zavisloti,0.053105,-0.018671,0.071845,-0.003174,0.157887,0.672205,1.000000,-0.227921,0.269778,-0.044805,0.111411
index_zavisloti_2,-0.023596,-0.019916,-0.012813,-0.125471,-0.125869,-0.677204,-0.227921,1.000000,0.876090,0.284829,-0.087597
index_ekonom_zatizeni,0.002962,-0.028942,0.022906,-0.125656,-0.046295,-0.336859,0.269778,0.876090,1.000000,0.259496,-0.031461
index_vzdelani,0.080349,0.110031,0.038690,0.135632,0.213890,-0.241072,-0.044805,0.284829,0.259496,1.000000,0.130286
kvartal,0.817007,0.052438,0.462257,0.318476,-0.014885,0.084287,0.111411,-0.087597,-0.031461,0.130286,1.000000

In [6]:
# 5 - Karlovarský kraj
obce_kraj5 = obce_kraje[obce_kraje["VOLKRAJ"] == 5]["KodObec"].tolist()
Pirati_kraj5 = Pirati[Pirati["KodObec"].isin(obce_kraj5)]

Pirati_kraj5[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.060343,0.426237,0.144760,-0.019830,-0.162934,-0.072474,0.152833,0.100566,0.198234,0.794604
Preferencni_hlasy_celkem_obce,0.060343,1.000000,0.077206,0.554451,-0.362041,-0.142548,-0.076334,0.174633,0.118518,0.237331,0.124064
podil_preferencnich_z_hlasu,0.426237,0.077206,1.000000,0.046924,-0.008635,-0.153449,-0.168476,0.014595,-0.080366,0.015275,0.568250
index_vybavenosti,0.144760,0.554451,0.046924,1.000000,-0.623569,-0.208325,-0.020178,0.250144,0.219419,0.149281,0.326726
index_socioekonomicky,-0.019830,-0.362041,-0.008635,-0.623569,1.000000,-0.011960,-0.100924,-0.111818,-0.159311,0.370208,-0.143572
index_stari,-0.162934,-0.142548,-0.153449,-0.208325,-0.011960,1.000000,0.655819,-0.717627,-0.296497,-0.247232,-0.150265
index_zavisloti,-0.072474,-0.076334,-0.168476,-0.020178,-0.100924,0.655819,1.000000,-0.156172,0.412891,-0.076087,-0.026990
index_zavisloti_2,0.152833,0.174633,0.014595,0.250144,-0.111818,-0.717627,-0.156172,1.000000,0.835123,0.199162,0.134207
index_ekonom_zatizeni,0.100566,0.118518,-0.080366,0.219419,-0.159311,-0.296497,0.412891,0.835123,1.000000,0.139804,0.108721
index_vzdelani,0.198234,0.237331,0.015275,0.149281,0.370208,-0.247232,-0.076087,0.199162,0.139804,1.000000,0.197802
kvartal,0.794604,0.124064,0.568250,0.326726,-0.143572,-0.150265,-0.026990,0.134207,0.108721,0.197802,1.000000

In [7]:
# 6 - Ústecký kraj
obce_kraj6 = obce_kraje[obce_kraje["VOLKRAJ"] == 6]["KodObec"].tolist()
Pirati_kraj6 = Pirati[Pirati["KodObec"].isin(obce_kraj6)]

Pirati_kraj6[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.002425,0.238759,0.052873,-0.030099,0.147971,0.168822,-0.001018,0.090521,-0.052204,0.740670
Preferencni_hlasy_celkem_obce,-0.002425,1.000000,0.027129,0.440633,-0.472813,-0.059058,0.008318,0.052638,0.051354,0.146961,0.074967
podil_preferencnich_z_hlasu,0.238759,0.027129,1.000000,-0.069565,0.015228,-0.028209,0.080784,0.088464,0.122494,0.000567,0.389036
index_vybavenosti,0.052873,0.440633,-0.069565,1.000000,-0.603648,-0.082134,0.021669,0.046858,0.053440,0.009538,0.209415
index_socioekonomicky,-0.030099,-0.472813,0.015228,-0.603648,1.000000,-0.013098,-0.067816,-0.023225,-0.057397,0.344524,-0.141170
index_stari,0.147971,-0.059058,-0.028209,-0.082134,-0.013098,1.000000,0.649492,-0.718590,-0.287827,-0.286810,0.089089
index_zavisloti,0.168822,0.008318,0.080784,0.021669,-0.067816,0.649492,1.000000,-0.088636,0.462674,-0.063948,0.169832
index_zavisloti_2,-0.001018,0.052638,0.088464,0.046858,-0.023225,-0.718590,-0.088636,1.000000,0.842030,0.340686,0.006912
index_ekonom_zatizeni,0.090521,0.051354,0.122494,0.053440,-0.057397,-0.287827,0.462674,0.842030,1.000000,0.268589,0.098127
index_vzdelani,-0.052204,0.146961,0.000567,0.009538,0.344524,-0.286810,-0.063948,0.340686,0.268589,1.000000,-0.026401
kvartal,0.740670,0.074967,0.389036,0.209415,-0.141170,0.089089,0.169832,0.006912,0.098127,-0.026401,1.000000

In [8]:
# 7 - Liberecký kraj
obce_kraj7 = obce_kraje[obce_kraje["VOLKRAJ"] == 7]["KodObec"].tolist()
Pirati_kraj7 = Pirati[Pirati["KodObec"].isin(obce_kraj7)]

Pirati_kraj7[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.029742,0.223659,0.151967,-0.027215,0.057203,-0.100159,-0.153568,-0.198286,-0.001401,0.795935
Preferencni_hlasy_celkem_obce,0.029742,1.000000,0.084474,0.335140,-0.298094,-0.036533,-0.026454,0.001918,-0.012683,0.130298,0.070081
podil_preferencnich_z_hlasu,0.223659,0.084474,1.000000,0.033486,-0.039869,-0.015874,-0.087126,-0.058379,-0.102228,-0.091943,0.342089
index_vybavenosti,0.151967,0.335140,0.033486,1.000000,-0.466579,-0.096433,-0.033404,0.008578,-0.010263,0.046042,0.344794
index_socioekonomicky,-0.027215,-0.298094,-0.039869,-0.466579,1.000000,0.221101,0.187048,-0.129322,-0.018483,0.463357,-0.099363
index_stari,0.057203,-0.036533,-0.015874,-0.096433,0.221101,1.000000,0.634322,-0.760614,-0.363581,-0.000746,0.032854
index_zavisloti,-0.100159,-0.026454,-0.087126,-0.033404,0.187048,0.634322,1.000000,-0.168561,0.389672,0.243425,-0.130867
index_zavisloti_2,-0.153568,0.001918,-0.058379,0.008578,-0.129322,-0.760614,-0.168561,1.000000,0.842092,0.171344,-0.205803
index_ekonom_zatizeni,-0.198286,-0.012683,-0.102228,-0.010263,-0.018483,-0.363581,0.389672,0.842092,1.000000,0.293284,-0.263892
index_vzdelani,-0.001401,0.130298,-0.091943,0.046042,0.463357,-0.000746,0.243425,0.171344,0.293284,1.000000,-0.029105
kvartal,0.795935,0.070081,0.342089,0.344794,-0.099363,0.032854,-0.130867,-0.205803,-0.263892,-0.029105,1.000000

In [9]:
# 8 - Královéhradecký kraj
obce_kraj8 = obce_kraje[obce_kraje["VOLKRAJ"] == 8]["KodObec"].tolist()
Pirati_kraj8 = Pirati[Pirati["KodObec"].isin(obce_kraj8)]

Pirati_kraj8[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.026317,0.272438,0.176061,-0.022807,-0.002158,0.035156,0.031001,0.046947,0.083728,0.802342
Preferencni_hlasy_celkem_obce,0.026317,1.000000,0.039541,0.295447,-0.236635,-0.076159,-0.028024,0.087062,0.054686,0.186366,0.081793
podil_preferencnich_z_hlasu,0.272438,0.039541,1.000000,-0.006443,-0.039910,-0.023820,-0.060012,0.015788,-0.023521,-0.076107,0.392285
index_vybavenosti,0.176061,0.295447,-0.006443,1.000000,-0.376723,-0.195268,-0.078337,0.164244,0.087662,0.207038,0.356368
index_socioekonomicky,-0.022807,-0.236635,-0.039910,-0.376723,1.000000,0.289106,0.146508,-0.267452,-0.131215,0.250226,-0.112709
index_stari,-0.002158,-0.076159,-0.023820,-0.195268,0.289106,1.000000,0.672809,-0.714814,-0.179497,-0.009676,-0.024255
index_zavisloti,0.035156,-0.028024,-0.060012,-0.078337,0.146508,0.672809,1.000000,-0.049473,0.567958,0.061459,-0.002987
index_zavisloti_2,0.031001,0.087062,0.015788,0.164244,-0.267452,-0.714814,-0.049473,1.000000,0.793951,0.080763,0.009382
index_ekonom_zatizeni,0.046947,0.054686,-0.023521,0.087662,-0.131215,-0.179497,0.567958,0.793951,1.000000,0.103966,0.005913
index_vzdelani,0.083728,0.186366,-0.076107,0.207038,0.250226,-0.009676,0.061459,0.080763,0.103966,1.000000,0.084164
kvartal,0.802342,0.081793,0.392285,0.356368,-0.112709,-0.024255,-0.002987,0.009382,0.005913,0.084164,1.000000

In [10]:
# 9 - Pardubický kraj
obce_kraj9 = obce_kraje[obce_kraje["VOLKRAJ"] == 9]["KodObec"].tolist()
Pirati_kraj9 = Pirati[Pirati["KodObec"].isin(obce_kraj9)]

Pirati_kraj9[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.042163,0.317057,0.174155,0.190115,-0.002327,-0.059649,-0.122854,-0.145177,0.116563,0.816700
Preferencni_hlasy_celkem_obce,0.042163,1.000000,0.055080,0.346103,-0.229863,-0.048990,-0.024256,0.029591,0.012551,0.219673,0.094945
podil_preferencnich_z_hlasu,0.317057,0.055080,1.000000,-0.067467,0.056527,0.019288,-0.001226,-0.032489,-0.029947,-0.037128,0.401186
index_vybavenosti,0.174155,0.346103,-0.067467,1.000000,-0.170410,0.014829,0.041827,-0.070748,-0.039391,0.258918,0.325213
index_socioekonomicky,0.190115,-0.229863,0.056527,-0.170410,1.000000,0.371927,0.235888,-0.298088,-0.131347,0.323177,0.190592
index_stari,-0.002327,-0.048990,0.019288,0.014829,0.371927,1.000000,0.639203,-0.754881,-0.308342,0.018970,0.071831
index_zavisloti,-0.059649,-0.024256,-0.001226,0.041827,0.235888,0.639203,1.000000,-0.140434,0.454010,0.135379,0.019636
index_zavisloti_2,-0.122854,0.029591,-0.032489,-0.070748,-0.298088,-0.754881,-0.140434,1.000000,0.818408,0.138317,-0.164363
index_ekonom_zatizeni,-0.145177,0.012551,-0.029947,-0.039391,-0.131347,-0.308342,0.454010,0.818408,1.000000,0.203046,-0.136516
index_vzdelani,0.116563,0.219673,-0.037128,0.258918,0.323177,0.018970,0.135379,0.138317,0.203046,1.000000,0.163559
kvartal,0.816700,0.094945,0.401186,0.325213,0.190592,0.071831,0.019636,-0.164363,-0.136516,0.163559,1.000000

In [11]:
# 10 - Kraj Vysočina
obce_kraj10 = obce_kraje[obce_kraje["VOLKRAJ"] == 10]["KodObec"].tolist()
Pirati_kraj10 = Pirati[Pirati["KodObec"].isin(obce_kraj10)]

Pirati_kraj10[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.081474,0.392741,0.216357,0.061782,0.029672,0.030752,-0.070316,-0.046268,0.052131,0.845497
Preferencni_hlasy_celkem_obce,0.081474,1.000000,0.037928,0.433159,-0.140258,-0.057824,-0.039015,0.011005,-0.011842,0.213965,0.120250
podil_preferencnich_z_hlasu,0.392741,0.037928,1.000000,-0.040533,0.039786,0.012447,0.025423,-0.019769,-0.003648,-0.045535,0.500502
index_vybavenosti,0.216357,0.433159,-0.040533,1.000000,-0.015960,-0.074289,-0.036483,-0.045681,-0.061559,0.284258,0.334435
index_socioekonomicky,0.061782,-0.140258,0.039786,-0.015960,1.000000,0.217121,0.176456,-0.111109,-0.001770,0.243857,0.061588
index_stari,0.029672,-0.057824,0.012447,-0.074289,0.217121,1.000000,0.692959,-0.623170,-0.175477,-0.015420,0.029090
index_zavisloti,0.030752,-0.039015,0.025423,-0.036483,0.176456,0.692959,1.000000,-0.124083,0.446007,0.169683,0.011496
index_zavisloti_2,-0.070316,0.011005,-0.019769,-0.045681,-0.111109,-0.623170,-0.124083,1.000000,0.832771,0.119262,-0.088158
index_ekonom_zatizeni,-0.046268,-0.011842,-0.003648,-0.061559,-0.001770,-0.175477,0.446007,0.832771,1.000000,0.202246,-0.073104
index_vzdelani,0.052131,0.213965,-0.045535,0.284258,0.243857,-0.015420,0.169683,0.119262,0.202246,1.000000,0.086095
kvartal,0.845497,0.120250,0.500502,0.334435,0.061588,0.029090,0.011496,-0.088158,-0.073104,0.086095,1.000000

In [12]:
# 11 - Jihomoravský kraj
obce_kraj11 = obce_kraje[obce_kraje["VOLKRAJ"] == 11]["KodObec"].tolist()
Pirati_kraj11 = Pirati[Pirati["KodObec"].isin(obce_kraj11)]

Pirati_kraj11[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.009712,0.358780,0.140571,0.072961,0.110650,0.059350,-0.182239,-0.132316,0.067423,0.785769
Preferencni_hlasy_celkem_obce,0.009712,1.000000,0.098008,0.135937,-0.401626,-0.018288,-0.018998,-0.002103,-0.015093,0.131929,0.024856
podil_preferencnich_z_hlasu,0.358780,0.098008,1.000000,0.036832,-0.020886,0.025874,0.001232,-0.094812,-0.089280,0.054805,0.496647
index_vybavenosti,0.140571,0.135937,0.036832,1.000000,-0.051907,-0.007723,0.029792,-0.064253,-0.040540,0.325558,0.336111
index_socioekonomicky,0.072961,-0.401626,-0.020886,-0.051907,1.000000,0.417765,0.422590,-0.232281,0.070467,0.310198,0.099734
index_stari,0.110650,-0.018288,0.025874,-0.007723,0.417765,1.000000,0.756052,-0.730730,-0.173488,0.055507,0.102578
index_zavisloti,0.059350,-0.018998,0.001232,0.029792,0.422590,0.756052,1.000000,-0.288867,0.414637,0.204168,0.048994
index_zavisloti_2,-0.182239,-0.002103,-0.094812,-0.064253,-0.232281,-0.730730,-0.288867,1.000000,0.751419,0.103216,-0.199679
index_ekonom_zatizeni,-0.132316,-0.015093,-0.089280,-0.040540,0.070467,-0.173488,0.414637,0.751419,1.000000,0.238821,-0.156029
index_vzdelani,0.067423,0.131929,0.054805,0.325558,0.310198,0.055507,0.204168,0.103216,0.238821,1.000000,0.152557
kvartal,0.785769,0.024856,0.496647,0.336111,0.099734,0.102578,0.048994,-0.199679,-0.156029,0.152557,1.000000

In [13]:
# 12 - Olomoucký kraj
obce_kraj12 = obce_kraje[obce_kraje["VOLKRAJ"] == 12]["KodObec"].tolist()
Pirati_kraj12 = Pirati[Pirati["KodObec"].isin(obce_kraj12)]

Pirati_kraj12[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.011083,0.248792,0.111293,-0.044035,0.010462,-0.098763,-0.165255,-0.201496,0.020238,0.764644
Preferencni_hlasy_celkem_obce,0.011083,1.000000,0.053490,0.286525,-0.255481,-0.042327,-0.012284,0.028391,0.020048,0.219907,0.062845
podil_preferencnich_z_hlasu,0.248792,0.053490,1.000000,0.016569,-0.019555,0.031779,-0.103052,-0.092772,-0.136831,0.046532,0.455150
index_vybavenosti,0.111293,0.286525,0.016569,1.000000,-0.300214,-0.099073,-0.036695,0.021024,0.001098,0.230675,0.328983
index_socioekonomicky,-0.044035,-0.255481,-0.019555,-0.300214,1.000000,0.324629,0.246791,-0.233212,-0.092010,0.356551,-0.075888
index_stari,0.010462,-0.042327,0.031779,-0.099073,0.324629,1.000000,0.712585,-0.589686,-0.188537,0.000694,0.043848
index_zavisloti,-0.098763,-0.012284,-0.103052,-0.036695,0.246791,0.712585,1.000000,-0.106188,0.400227,0.079765,-0.067444
index_zavisloti_2,-0.165255,0.028391,-0.092772,0.021024,-0.233212,-0.589686,-0.106188,1.000000,0.868736,0.030786,-0.219107
index_ekonom_zatizeni,-0.201496,0.020048,-0.136831,0.001098,-0.092010,-0.188537,0.400227,0.868736,1.000000,0.068333,-0.235528
index_vzdelani,0.020238,0.219907,0.046532,0.230675,0.356551,0.000694,0.079765,0.030786,0.068333,1.000000,0.125978
kvartal,0.764644,0.062845,0.455150,0.328983,-0.075888,0.043848,-0.067444,-0.219107,-0.235528,0.125978,1.000000

In [14]:
# 13 - Zlínský kraj
obce_kraj13 = obce_kraje[obce_kraje["VOLKRAJ"] == 13]["KodObec"].tolist()
Pirati_kraj13 = Pirati[Pirati["KodObec"].isin(obce_kraj13)]

Pirati_kraj13[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.000120,0.168862,0.056271,-0.148076,-0.069519,-0.077485,0.057350,0.000183,0.024010,0.761233
Preferencni_hlasy_celkem_obce,0.000120,1.000000,0.066059,0.381027,-0.298930,-0.125315,-0.058400,0.146486,0.094665,0.350016,0.103838
podil_preferencnich_z_hlasu,0.168862,0.066059,1.000000,-0.059750,-0.046785,0.031396,0.010599,-0.016391,-0.007848,-0.028092,0.345471
index_vybavenosti,0.056271,0.381027,-0.059750,1.000000,-0.305097,-0.140217,-0.009062,0.172348,0.151650,0.435386,0.288675
index_socioekonomicky,-0.148076,-0.298930,-0.046785,-0.305097,1.000000,0.325973,0.239118,-0.302843,-0.115782,-0.026794,-0.209441
index_stari,-0.069519,-0.125315,0.031396,-0.140217,0.325973,1.000000,0.780667,-0.754254,-0.163373,-0.171861,-0.109003
index_zavisloti,-0.077485,-0.058400,0.010599,-0.009062,0.239118,0.780667,1.000000,-0.237695,0.457573,-0.015429,-0.076581
index_zavisloti_2,0.057350,0.146486,-0.016391,0.172348,-0.302843,-0.754254,-0.237695,1.000000,0.754925,0.189061,0.119138
index_ekonom_zatizeni,0.000183,0.094665,-0.007848,0.151650,-0.115782,-0.163373,0.457573,0.754925,1.000000,0.162614,0.057355
index_vzdelani,0.024010,0.350016,-0.028092,0.435386,-0.026794,-0.171861,-0.015429,0.189061,0.162614,1.000000,0.121042
kvartal,0.761233,0.103838,0.345471,0.288675,-0.209441,-0.109003,-0.076581,0.119138,0.057355,0.121042,1.000000

In [15]:
# 14 - Moravskoslezský kraj
obce_kraj14 = obce_kraje[obce_kraje["VOLKRAJ"] == 14]["KodObec"].tolist()
Pirati_kraj14 = Pirati[Pirati["KodObec"].isin(obce_kraj14)]

Pirati_kraj14[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.032213,0.415276,0.197827,0.009862,0.057432,0.199448,0.066071,0.207401,0.178180,0.798185
Preferencni_hlasy_celkem_obce,0.032213,1.000000,0.115311,0.259037,-0.692080,-0.086105,-0.072881,0.055250,-0.002682,0.108339,0.063029
podil_preferencnich_z_hlasu,0.415276,0.115311,1.000000,0.095502,0.011081,0.146670,0.160952,-0.093747,0.031925,0.150775,0.580042
index_vybavenosti,0.197827,0.259037,0.095502,1.000000,-0.294678,-0.209549,-0.059178,0.187158,0.128848,0.372562,0.363058
index_socioekonomicky,0.009862,-0.692080,0.011081,-0.294678,1.000000,0.231405,0.207735,-0.177087,-0.010408,0.268340,0.036446
index_stari,0.057432,-0.086105,0.146670,-0.209549,0.231405,1.000000,0.787715,-0.762738,-0.123480,0.038104,0.103616
index_zavisloti,0.199448,-0.072881,0.160952,-0.059178,0.207735,0.787715,1.000000,-0.286605,0.470937,0.179738,0.212365
index_zavisloti_2,0.066071,0.055250,-0.093747,0.187158,-0.177087,-0.762738,-0.286605,1.000000,0.710186,0.067155,-0.023095
index_ekonom_zatizeni,0.207401,-0.002682,0.031925,0.128848,-0.010408,-0.123480,0.470937,0.710186,1.000000,0.193915,0.134789
index_vzdelani,0.178180,0.108339,0.150775,0.372562,0.268340,0.038104,0.179738,0.067155,0.193915,1.000000,0.343065
kvartal,0.798185,0.063029,0.580042,0.363058,0.036446,0.103616,0.212365,-0.023095,0.134789,0.343065,1.000000