# Korelace podílu prefenčních hlasů pro kandidátky SPOLU a indexů pro obce v jednotlivých krajích

Korelace indexů s podíly prefenčních hlasů v obcích v daných krajích. Vždy pro každou stranu zvlášť.

In [1]:
import pandas as pd

# obce_kraje
obce_kraje = pd.read_csv("obce_kraje.csv")
obce_kraje = obce_kraje.rename(columns={"OBEC_PREZ": "KodObec"})

# hlasy stran za obec
hlasy_strany = pd.read_csv("hlasy_strany_obce.csv")

In [2]:
# Spolu - kandidátky s aspoň jednou ženou

strany_s_kandidatkami = pd.read_csv("strany_s_kandidatkami_obec.csv")
Spolu = strany_s_kandidatkami[strany_s_kandidatkami["KSTRANA"] == 11]

# merge s celkovým počtem hlasů pro stranu + výpočet podílu preferenčních hlasů
Spolu = Spolu.merge(hlasy_strany, on=["KodObec", "KSTRANA"], how="left")
Spolu["podil_preferencnich_z_hlasu"] = Spolu["Preferencni_hlasy_celkem_obce"] / Spolu["hlasy_strany_celkem"]

In [3]:
# 2 - Středočeský kraj
obce_kraj2 = obce_kraje[obce_kraje["VOLKRAJ"] == 2]["KodObec"].tolist()
Spolu_kraj2 = Spolu[Spolu["KodObec"].isin(obce_kraj2)]

Spolu_kraj2[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.028991,0.124008,0.067445,0.025590,0.044989,0.074882,-0.038845,0.008199,0.045356,0.781500
Preferencni_hlasy_celkem_obce,0.028991,1.000000,0.081878,0.563015,-0.142044,0.091686,0.078248,-0.084503,-0.033872,0.289416,0.022961
podil_preferencnich_z_hlasu,0.124008,0.081878,1.000000,-0.013253,0.025999,0.046511,0.032193,-0.028975,-0.008338,0.041426,0.234783
index_vybavenosti,0.067445,0.563015,-0.013253,1.000000,-0.074860,0.158648,0.183637,-0.167301,-0.049516,0.301869,0.103481
index_socioekonomicky,0.025590,-0.142044,0.025999,-0.074860,1.000000,0.506901,0.390478,-0.308674,-0.059801,0.389998,0.036921
index_stari,0.044989,0.091686,0.046511,0.158648,0.506901,1.000000,0.642804,-0.703914,-0.287654,0.106883,0.065660
index_zavisloti,0.074882,0.078248,0.032193,0.183637,0.390478,0.642804,1.000000,-0.260164,0.359404,0.200691,0.091641
index_zavisloti_2,-0.038845,-0.084503,-0.028975,-0.167301,-0.308674,-0.703914,-0.260164,1.000000,0.807543,0.015816,-0.102007
index_ekonom_zatizeni,0.008199,-0.033872,-0.008338,-0.049516,-0.059801,-0.287654,0.359404,0.807543,1.000000,0.137876,-0.042607
index_vzdelani,0.045356,0.289416,0.041426,0.301869,0.389998,0.106883,0.200691,0.015816,0.137876,1.000000,0.062053
kvartal,0.781500,0.022961,0.234783,0.103481,0.036921,0.065660,0.091641,-0.102007,-0.042607,0.062053,1.000000

In [4]:
# 3 - Jihočeský kraj
obce_kraj3 = obce_kraje[obce_kraje["VOLKRAJ"] == 3]["KodObec"].tolist()
Spolu_kraj3 = Spolu[Spolu["KodObec"].isin(obce_kraj3)]

Spolu_kraj3[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.012755,0.068380,-0.001096,-0.068803,-0.077841,-0.067416,0.040842,-0.002785,0.028199,0.754928
Preferencni_hlasy_celkem_obce,-0.012755,1.000000,0.040039,0.363066,-0.196184,-0.022821,-0.000512,0.004343,0.003544,0.197285,0.023565
podil_preferencnich_z_hlasu,0.068380,0.040039,1.000000,0.023047,0.024207,0.143980,0.118620,-0.127271,-0.044084,0.067511,0.286727
index_vybavenosti,-0.001096,0.363066,0.023047,1.000000,-0.289584,-0.016323,-0.007394,-0.096625,-0.089687,0.160155,0.128490
index_socioekonomicky,-0.068803,-0.196184,0.024207,-0.289584,1.000000,0.321472,0.268286,-0.212594,-0.033174,0.257597,-0.058407
index_stari,-0.077841,-0.022821,0.143980,-0.016323,0.321472,1.000000,0.680527,-0.700087,-0.226328,0.003050,0.006749
index_zavisloti,-0.067416,-0.000512,0.118620,-0.007394,0.268286,0.680527,1.000000,-0.112107,0.477778,0.138017,-0.019069
index_zavisloti_2,0.040842,0.004343,-0.127271,-0.096625,-0.212594,-0.700087,-0.112107,1.000000,0.819381,0.129769,-0.091229
index_ekonom_zatizeni,-0.002785,0.003544,-0.044084,-0.089687,-0.033174,-0.226328,0.477778,0.819381,1.000000,0.194390,-0.091652
index_vzdelani,0.028199,0.197285,0.067511,0.160155,0.257597,0.003050,0.138017,0.129769,0.194390,1.000000,0.050870
kvartal,0.754928,0.023565,0.286727,0.128490,-0.058407,0.006749,-0.019069,-0.091229,-0.091652,0.050870,1.000000

In [5]:
# 4 - Plzeňský kraj
obce_kraj4 = obce_kraje[obce_kraje["VOLKRAJ"] == 4]["KodObec"].tolist()
Spolu_kraj4 = Spolu[Spolu["KodObec"].isin(obce_kraj4)]

Spolu_kraj4[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.007885,0.120120,0.054956,0.034771,0.024237,0.048208,-0.038825,-0.014970,0.066549,0.767139
Preferencni_hlasy_celkem_obce,0.007885,1.000000,0.093454,0.222389,-0.133552,-0.012039,-0.019642,-0.020741,-0.030053,0.116658,0.032473
podil_preferencnich_z_hlasu,0.120120,0.093454,1.000000,0.019293,0.067558,-0.046755,0.018065,0.012176,0.020820,0.034492,0.239544
index_vybavenosti,0.054956,0.222389,0.019293,1.000000,-0.216361,-0.011985,-0.009855,-0.144265,-0.147446,0.131479,0.223737
index_socioekonomicky,0.034771,-0.133552,0.067558,-0.216361,1.000000,0.194483,0.136905,-0.085955,-0.018479,0.232904,0.036527
index_stari,0.024237,-0.012039,-0.046755,-0.011985,0.194483,1.000000,0.671524,-0.674980,-0.341184,-0.248305,-0.014808
index_zavisloti,0.048208,-0.019642,0.018065,-0.009855,0.136905,0.671524,1.000000,-0.222605,0.265745,-0.049535,0.045284
index_zavisloti_2,-0.038825,-0.020741,0.012176,-0.144265,-0.085955,-0.674980,-0.222605,1.000000,0.880698,0.290533,-0.031671
index_ekonom_zatizeni,-0.014970,-0.030053,0.020820,-0.147446,-0.018479,-0.341184,0.265745,0.880698,1.000000,0.263227,-0.009316
index_vzdelani,0.066549,0.116658,0.034492,0.131479,0.232904,-0.248305,-0.049535,0.290533,0.263227,1.000000,0.182267
kvartal,0.767139,0.032473,0.239544,0.223737,0.036527,-0.014808,0.045284,-0.031671,-0.009316,0.182267,1.000000

In [6]:
# 5 - Karlovarský kraj
obce_kraj5 = obce_kraje[obce_kraje["VOLKRAJ"] == 5]["KodObec"].tolist()
Spolu_kraj5 = Spolu[Spolu["KodObec"].isin(obce_kraj5)]

Spolu_kraj5[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.010067,0.179726,0.031563,0.065553,-0.107454,-0.074156,0.055944,0.011052,0.033370,0.742572
Preferencni_hlasy_celkem_obce,-0.010067,1.000000,0.083642,0.517680,-0.342880,-0.150860,-0.078283,0.187353,0.131007,0.259574,0.111206
podil_preferencnich_z_hlasu,0.179726,0.083642,1.000000,-0.007038,0.003549,-0.159367,-0.071760,0.073452,0.028662,0.134755,0.326083
index_vybavenosti,0.031563,0.517680,-0.007038,1.000000,-0.618620,-0.216486,-0.025961,0.257557,0.225229,0.156888,0.246035
index_socioekonomicky,0.065553,-0.342880,0.003549,-0.618620,1.000000,-0.012980,-0.101386,-0.108478,-0.156943,0.362101,-0.024883
index_stari,-0.107454,-0.150860,-0.159367,-0.216486,-0.012980,1.000000,0.656262,-0.726865,-0.313404,-0.274341,-0.274029
index_zavisloti,-0.074156,-0.078283,-0.071760,-0.025961,-0.101386,0.656262,1.000000,-0.166058,0.398244,-0.087961,-0.182672
index_zavisloti_2,0.055944,0.187353,0.073452,0.257557,-0.108478,-0.726865,-0.166058,1.000000,0.838413,0.231806,0.117010
index_ekonom_zatizeni,0.011052,0.131007,0.028662,0.225229,-0.156943,-0.313404,0.398244,0.838413,1.000000,0.165432,0.007877
index_vzdelani,0.033370,0.259574,0.134755,0.156888,0.362101,-0.274341,-0.087961,0.231806,0.165432,1.000000,0.186905
kvartal,0.742572,0.111206,0.326083,0.246035,-0.024883,-0.274029,-0.182672,0.117010,0.007877,0.186905,1.000000

In [7]:
# 6 - Ústecký kraj
obce_kraj6 = obce_kraje[obce_kraje["VOLKRAJ"] == 6]["KodObec"].tolist()
Spolu_kraj6 = Spolu[Spolu["KodObec"].isin(obce_kraj6)]

Spolu_kraj6[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.032045,0.112652,-0.021281,0.015567,0.078039,0.177925,0.019608,0.113845,-0.116306,0.713315
Preferencni_hlasy_celkem_obce,-0.032045,1.000000,0.046727,0.470404,-0.472714,-0.062899,0.010671,0.056616,0.056364,0.170795,0.057221
podil_preferencnich_z_hlasu,0.112652,0.046727,1.000000,-0.084589,-0.045718,0.053537,0.055131,-0.003241,0.026955,-0.128141,0.262991
index_vybavenosti,-0.021281,0.470404,-0.084589,1.000000,-0.604858,-0.090612,0.021004,0.052416,0.058205,0.004234,0.193753
index_socioekonomicky,0.015567,-0.472714,-0.045718,-0.604858,1.000000,-0.004625,-0.066111,-0.028067,-0.060869,0.342421,-0.108711
index_stari,0.078039,-0.062899,0.053537,-0.090612,-0.004625,1.000000,0.647273,-0.722795,-0.295402,-0.287662,0.075826
index_zavisloti,0.177925,0.010671,0.055131,0.021004,-0.066111,0.647273,1.000000,-0.094523,0.456923,-0.070682,0.093070
index_zavisloti_2,0.019608,0.056616,-0.003241,0.052416,-0.028067,-0.722795,-0.094523,1.000000,0.842334,0.341310,-0.049402
index_ekonom_zatizeni,0.113845,0.056364,0.026955,0.058205,-0.060869,-0.295402,0.456923,0.842334,1.000000,0.266697,0.006246
index_vzdelani,-0.116306,0.170795,-0.128141,0.004234,0.342421,-0.287662,-0.070682,0.341310,0.266697,1.000000,-0.104422
kvartal,0.713315,0.057221,0.262991,0.193753,-0.108711,0.075826,0.093070,-0.049402,0.006246,-0.104422,1.000000

In [8]:
# 7 - Liberecký kraj
obce_kraj7 = obce_kraje[obce_kraje["VOLKRAJ"] == 7]["KodObec"].tolist()
Spolu_kraj7 = Spolu[Spolu["KodObec"].isin(obce_kraj7)]

Spolu_kraj7[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.000338,0.006978,0.093278,-0.052777,0.000360,0.039064,-0.004466,0.017202,-0.045897,0.767184
Preferencni_hlasy_celkem_obce,0.000338,1.000000,0.152303,0.366143,-0.311232,-0.039363,-0.025130,0.006111,-0.008041,0.146067,0.015798
podil_preferencnich_z_hlasu,0.006978,0.152303,1.000000,0.149274,0.052231,0.018944,0.097262,0.035541,0.086434,0.148475,0.215400
index_vybavenosti,0.093278,0.366143,0.149274,1.000000,-0.466579,-0.096433,-0.033404,0.008578,-0.010263,0.046042,0.199102
index_socioekonomicky,-0.052777,-0.311232,0.052231,-0.466579,1.000000,0.221101,0.187048,-0.129322,-0.018483,0.463357,-0.003558
index_stari,0.000360,-0.039363,0.018944,-0.096433,0.221101,1.000000,0.634322,-0.760614,-0.363581,-0.000746,0.005340
index_zavisloti,0.039064,-0.025130,0.097262,-0.033404,0.187048,0.634322,1.000000,-0.168561,0.389672,0.243425,0.085338
index_zavisloti_2,-0.004466,0.006111,0.035541,0.008578,-0.129322,-0.760614,-0.168561,1.000000,0.842092,0.171344,0.030262
index_ekonom_zatizeni,0.017202,-0.008041,0.086434,-0.010263,-0.018483,-0.363581,0.389672,0.842092,1.000000,0.293284,0.074968
index_vzdelani,-0.045897,0.146067,0.148475,0.046042,0.463357,-0.000746,0.243425,0.171344,0.293284,1.000000,0.070955
kvartal,0.767184,0.015798,0.215400,0.199102,-0.003558,0.005340,0.085338,0.030262,0.074968,0.070955,1.000000

In [9]:
# 8 - Královéhradecký kraj
obce_kraj8 = obce_kraje[obce_kraje["VOLKRAJ"] == 8]["KodObec"].tolist()
Spolu_kraj8 = Spolu[Spolu["KodObec"].isin(obce_kraj8)]

Spolu_kraj8[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.013582,0.033257,0.095035,0.087662,0.116106,0.123157,-0.064468,0.021165,0.062635,0.724019
Preferencni_hlasy_celkem_obce,-0.013582,1.000000,0.075597,0.316464,-0.238955,-0.080691,-0.026077,0.094013,0.062204,0.203486,0.052130
podil_preferencnich_z_hlasu,0.033257,0.075597,1.000000,0.087550,-0.025054,0.069681,0.139041,-0.013969,0.072698,0.069897,0.222011
index_vybavenosti,0.095035,0.316464,0.087550,1.000000,-0.372136,-0.187323,-0.075932,0.149675,0.078171,0.209028,0.268580
index_socioekonomicky,0.087662,-0.238955,-0.025054,-0.372136,1.000000,0.292616,0.149644,-0.271345,-0.134448,0.248806,-0.011265
index_stari,0.116106,-0.080691,0.069681,-0.187323,0.292616,1.000000,0.673422,-0.717373,-0.187041,-0.008743,0.066053
index_zavisloti,0.123157,-0.026077,0.139041,-0.075932,0.149644,0.673422,1.000000,-0.055753,0.559957,0.059301,0.119375
index_zavisloti_2,-0.064468,0.094013,-0.013969,0.149675,-0.271345,-0.717373,-0.055753,1.000000,0.796013,0.075692,-0.016386
index_ekonom_zatizeni,0.021165,0.062204,0.072698,0.078171,-0.134448,-0.187041,0.559957,0.796013,1.000000,0.098760,0.058771
index_vzdelani,0.062635,0.203486,0.069897,0.209028,0.248806,-0.008743,0.059301,0.075692,0.098760,1.000000,0.143985
kvartal,0.724019,0.052130,0.222011,0.268580,-0.011265,0.066053,0.119375,-0.016386,0.058771,0.143985,1.000000

In [10]:
# 9 - Pardubický kraj
obce_kraj9 = obce_kraje[obce_kraje["VOLKRAJ"] == 9]["KodObec"].tolist()
Spolu_kraj9 = Spolu[Spolu["KodObec"].isin(obce_kraj9)]

Spolu_kraj9[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.018988,0.165168,0.028910,0.136447,-0.013519,0.118694,0.006729,0.072193,0.119288,0.760939
Preferencni_hlasy_celkem_obce,-0.018988,1.000000,0.091574,0.364914,-0.232085,-0.049454,-0.019295,0.028590,0.015209,0.228051,0.041977
podil_preferencnich_z_hlasu,0.165168,0.091574,1.000000,-0.011966,0.051851,0.020251,0.110173,-0.011986,0.050460,0.010240,0.205602
index_vybavenosti,0.028910,0.364914,-0.011966,1.000000,-0.181907,-0.005162,0.048887,-0.056967,-0.024491,0.269861,0.150517
index_socioekonomicky,0.136447,-0.232085,0.051851,-0.181907,1.000000,0.351108,0.247822,-0.251359,-0.090185,0.330185,0.108918
index_stari,-0.013519,-0.049454,0.020251,-0.005162,0.351108,1.000000,0.608635,-0.749774,-0.341718,0.000044,-0.007931
index_zavisloti,0.118694,-0.019295,0.110173,0.048887,0.247822,0.608635,1.000000,-0.132505,0.436484,0.115764,0.107323
index_zavisloti_2,0.006729,0.028590,-0.011986,-0.056967,-0.251359,-0.749774,-0.132505,1.000000,0.833942,0.153932,-0.044845
index_ekonom_zatizeni,0.072193,0.015209,0.050460,-0.024491,-0.090185,-0.341718,0.436484,0.833942,1.000000,0.204180,0.019047
index_vzdelani,0.119288,0.228051,0.010240,0.269861,0.330185,0.000044,0.115764,0.153932,0.204180,1.000000,0.187086
kvartal,0.760939,0.041977,0.205602,0.150517,0.108918,-0.007931,0.107323,-0.044845,0.019047,0.187086,1.000000

In [11]:
# 10 - Kraj Vysočina
obce_kraj10 = obce_kraje[obce_kraje["VOLKRAJ"] == 10]["KodObec"].tolist()
Spolu_kraj10 = Spolu[Spolu["KodObec"].isin(obce_kraj10)]

Spolu_kraj10[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.029196,0.116320,0.069925,0.029358,-0.012167,0.023315,-0.004833,0.008652,0.006296,0.777978
Preferencni_hlasy_celkem_obce,0.029196,1.000000,0.053900,0.437800,-0.123881,-0.046653,-0.032427,0.002161,-0.016108,0.212567,0.103609
podil_preferencnich_z_hlasu,0.116320,0.053900,1.000000,0.022425,0.102659,0.004664,0.024109,0.078284,0.083372,0.018837,0.249010
index_vybavenosti,0.069925,0.437800,0.022425,1.000000,-0.016207,-0.065415,-0.037762,-0.056663,-0.071645,0.276177,0.253626
index_socioekonomicky,0.029358,-0.123881,0.102659,-0.016207,1.000000,0.206480,0.184806,-0.088875,0.023386,0.256735,0.003092
index_stari,-0.012167,-0.046653,0.004664,-0.065415,0.206480,1.000000,0.686081,-0.622507,-0.174636,-0.012240,0.013187
index_zavisloti,0.023315,-0.032427,0.024109,-0.037762,0.184806,0.686081,1.000000,-0.108743,0.459136,0.174581,0.037668
index_zavisloti_2,-0.004833,0.002161,0.078284,-0.056663,-0.088875,-0.622507,-0.108743,1.000000,0.833170,0.119730,-0.034330
index_ekonom_zatizeni,0.008652,-0.016108,0.083372,-0.071645,0.023386,-0.174636,0.459136,0.833170,1.000000,0.204121,-0.009724
index_vzdelani,0.006296,0.212567,0.018837,0.276177,0.256735,-0.012240,0.174581,0.119730,0.204121,1.000000,0.076496
kvartal,0.777978,0.103609,0.249010,0.253626,0.003092,0.013187,0.037668,-0.034330,-0.009724,0.076496,1.000000

In [12]:
# 11 - Jihomoravský kraj
obce_kraj11 = obce_kraje[obce_kraje["VOLKRAJ"] == 11]["KodObec"].tolist()
Spolu_kraj11 = Spolu[Spolu["KodObec"].isin(obce_kraj11)]

Spolu_kraj11[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.002521,0.106919,0.071739,-0.114754,-0.054844,-0.094181,0.058356,-0.009086,-0.062363,0.812875
Preferencni_hlasy_celkem_obce,0.002521,1.000000,0.077609,0.158474,-0.400478,-0.017574,-0.015941,-0.002077,-0.012819,0.142989,-0.007678
podil_preferencnich_z_hlasu,0.106919,0.077609,1.000000,-0.004384,-0.003600,0.018889,0.079681,-0.008725,0.046042,0.000401,0.207913
index_vybavenosti,0.071739,0.158474,-0.004384,1.000000,-0.054518,-0.014971,0.034160,-0.054009,-0.027697,0.323122,0.095618
index_socioekonomicky,-0.114754,-0.400478,-0.003600,-0.054518,1.000000,0.420173,0.415412,-0.239297,0.057157,0.307592,-0.078947
index_stari,-0.054844,-0.017574,0.018889,-0.014971,0.420173,1.000000,0.744185,-0.732458,-0.184268,0.060653,-0.074712
index_zavisloti,-0.094181,-0.015941,0.079681,0.034160,0.415412,0.744185,1.000000,-0.275767,0.420957,0.200271,-0.085506
index_zavisloti_2,0.058356,-0.002077,-0.008725,-0.054009,-0.239297,-0.732458,-0.275767,1.000000,0.755822,0.096026,0.062497
index_ekonom_zatizeni,-0.009086,-0.012819,0.046042,-0.027697,0.057157,-0.184268,0.420957,0.755822,1.000000,0.227040,0.000731
index_vzdelani,-0.062363,0.142989,0.000401,0.323122,0.307592,0.060653,0.200271,0.096026,0.227040,1.000000,-0.047681
kvartal,0.812875,-0.007678,0.207913,0.095618,-0.078947,-0.074712,-0.085506,0.062497,0.000731,-0.047681,1.000000

In [13]:
# 12 - Olomoucký kraj
obce_kraj12 = obce_kraje[obce_kraje["VOLKRAJ"] == 12]["KodObec"].tolist()
Spolu_kraj12 = Spolu[Spolu["KodObec"].isin(obce_kraj12)]

Spolu_kraj12[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,0.037133,0.006796,0.143625,-0.307486,-0.086456,-0.143170,-0.030836,-0.099717,-0.141317,0.807880
Preferencni_hlasy_celkem_obce,0.037133,1.000000,0.039816,0.321187,-0.270243,-0.053985,-0.015179,0.039819,0.029153,0.237960,-0.012262
podil_preferencnich_z_hlasu,0.006796,0.039816,1.000000,-0.067369,-0.066324,0.016556,0.110178,0.062203,0.112209,-0.043434,0.068656
index_vybavenosti,0.143625,0.321187,-0.067369,1.000000,-0.298596,-0.100458,-0.038774,0.020527,-0.000381,0.230675,0.126139
index_socioekonomicky,-0.307486,-0.270243,-0.066324,-0.298596,1.000000,0.326111,0.248965,-0.233003,-0.090853,0.356551,-0.239954
index_stari,-0.086456,-0.053985,0.016556,-0.100458,0.326111,1.000000,0.712402,-0.590123,-0.189346,0.000694,-0.052593
index_zavisloti,-0.143170,-0.015179,0.110178,-0.038774,0.248965,0.712402,1.000000,-0.106667,0.399581,0.079765,-0.059853
index_zavisloti_2,-0.030836,0.039819,0.062203,0.020527,-0.233003,-0.590123,-0.106667,1.000000,0.868846,0.030786,-0.032980
index_ekonom_zatizeni,-0.099717,0.029153,0.112209,-0.000381,-0.090853,-0.189346,0.399581,0.868846,1.000000,0.068333,-0.060208
index_vzdelani,-0.141317,0.237960,-0.043434,0.230675,0.356551,0.000694,0.079765,0.030786,0.068333,1.000000,-0.173664
kvartal,0.807880,-0.012262,0.068656,0.126139,-0.239954,-0.052593,-0.059853,-0.032980,-0.060208,-0.173664,1.000000

In [14]:
# 13 - Zlínský kraj
obce_kraj13 = obce_kraje[obce_kraje["VOLKRAJ"] == 13]["KodObec"].tolist()
Spolu_kraj13 = Spolu[Spolu["KodObec"].isin(obce_kraj13)]

Spolu_kraj13[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.017067,0.011451,-0.018863,0.179555,-0.052905,-0.078014,-0.023430,-0.074120,0.025791,0.635421
Preferencni_hlasy_celkem_obce,-0.017067,1.000000,0.069861,0.441073,-0.329816,-0.131561,-0.054945,0.156190,0.105881,0.385396,0.064337
podil_preferencnich_z_hlasu,0.011451,0.069861,1.000000,0.039981,0.036168,0.111845,0.063686,-0.096068,-0.044943,-0.089767,0.114607
index_vybavenosti,-0.018863,0.441073,0.039981,1.000000,-0.305097,-0.140217,-0.009062,0.172348,0.151650,0.435386,0.186851
index_socioekonomicky,0.179555,-0.329816,0.036168,-0.305097,1.000000,0.325973,0.239118,-0.302843,-0.115782,-0.026794,0.093275
index_stari,-0.052905,-0.131561,0.111845,-0.140217,0.325973,1.000000,0.780667,-0.754254,-0.163373,-0.171861,-0.018610
index_zavisloti,-0.078014,-0.054945,0.063686,-0.009062,0.239118,0.780667,1.000000,-0.237695,0.457573,-0.015429,-0.063764
index_zavisloti_2,-0.023430,0.156190,-0.096068,0.172348,-0.302843,-0.754254,-0.237695,1.000000,0.754925,0.189061,-0.073218
index_ekonom_zatizeni,-0.074120,0.105881,-0.044943,0.151650,-0.115782,-0.163373,0.457573,0.754925,1.000000,0.162614,-0.110075
index_vzdelani,0.025791,0.385396,-0.089767,0.435386,-0.026794,-0.171861,-0.015429,0.189061,0.162614,1.000000,0.106953
kvartal,0.635421,0.064337,0.114607,0.186851,0.093275,-0.018610,-0.063764,-0.073218,-0.110075,0.106953,1.000000

In [15]:
# 14 - Moravskoslezský kraj
obce_kraj14 = obce_kraje[obce_kraje["VOLKRAJ"] == 14]["KodObec"].tolist()
Spolu_kraj14 = Spolu[Spolu["KodObec"].isin(obce_kraj14)]

Spolu_kraj14[['Podil_preferencni_hlasy_zeny_obce', 'Preferencni_hlasy_celkem_obce', 'podil_preferencnich_z_hlasu', 'index_vybavenosti', 'index_socioekonomicky', 'index_stari', 'index_zavisloti', 'index_zavisloti_2', 'index_ekonom_zatizeni', 'index_vzdelani', 'kvartal']].corr()

,Podil_preferencni_hlasy_zeny_obce,Preferencni_hlasy_celkem_obce,podil_preferencnich_z_hlasu,index_vybavenosti,index_socioekonomicky,index_stari,index_zavisloti,index_zavisloti_2,index_ekonom_zatizeni,index_vzdelani,kvartal
Podil_preferencni_hlasy_zeny_obce,1.000000,-0.000264,0.028981,-0.006631,-0.012894,-0.044723,-0.012674,0.100592,0.083441,0.099803,0.671839
Preferencni_hlasy_celkem_obce,-0.000264,1.000000,0.089612,0.307196,-0.676216,-0.096477,-0.072650,0.069827,0.010755,0.136609,0.052928
podil_preferencnich_z_hlasu,0.028981,0.089612,1.000000,0.031947,0.169279,0.050404,0.112048,0.016156,0.097583,0.114776,0.118356
index_vybavenosti,-0.006631,0.307196,0.031947,1.000000,-0.293663,-0.215770,-0.066173,0.190929,0.127265,0.378526,0.156918
index_socioekonomicky,-0.012894,-0.676216,0.169279,-0.293663,1.000000,0.229593,0.206287,-0.176509,-0.010462,0.264760,-0.026991
index_stari,-0.044723,-0.096477,0.050404,-0.215770,0.229593,1.000000,0.790126,-0.763576,-0.120805,0.017731,-0.016770
index_zavisloti,-0.012674,-0.072650,0.112048,-0.066173,0.206287,0.790126,1.000000,-0.291105,0.470106,0.157938,0.023183
index_zavisloti_2,0.100592,0.069827,0.016156,0.190929,-0.176509,-0.763576,-0.291105,1.000000,0.707534,0.077231,0.067226
index_ekonom_zatizeni,0.083441,0.010755,0.097583,0.127265,-0.010462,-0.120805,0.470106,0.707534,1.000000,0.187915,0.079145
index_vzdelani,0.099803,0.136609,0.114776,0.378526,0.264760,0.017731,0.157938,0.077231,0.187915,1.000000,0.214543
kvartal,0.671839,0.052928,0.118356,0.156918,-0.026991,-0.016770,0.023183,0.067226,0.079145,0.214543,1.000000